### ISSUE TITLE
do we want MHC filtered out of v2d and v2g?

### ISSUE THREAD

**Issue by elipapa** [opentargets/genetics#101]
so far we have included them. 

Sum Stats in that region are already filtered

**Comment by iandunham** [comment]
Previously in postgap, these were filtered under the assumption that because the input was filtered, then there should be no assignments there. However there will be edge effects. Probably OK to leave in at first.

**Comment by peatroot** [comment]
The data is not filtered, but we currently can't handle the MHC in the locus plot, so there's a few loci that the API just returns a *too dense* message. We'll have to aggregate the data somehow to change this.
