### ISSUE TITLE
filter out fantom5 enhancers > 2 Mb

### ISSUE THREAD

**Issue by elipapa** [opentargets/genetics#105]
we have filtered pChic data from Javierre to be < 2.45Mb. 

for consistency we should filter the Fantom5 enhancer data. Some analysis of the current data is at https://github.com/opentargets/v2g_data/blob/master/analysis/fantom5.ipynb

**Comment by ElaineMcA** [comment]
Pchic/fantom5 has been filtered by @eliseo. @edm1  preparing the newest versions of all files for a final run of the pipeline.

**Comment by edm1** [comment]
Fantom5 data now has trans-interactions (cross-chromosome and >1,068,265 bases) removed.

This has been updated in `gs://genetics-portal-data`.

https://github.com/opentargets/v2g_data/commit/f55cb67e5187f44cb37cad5a5db597b44a42c370
