### ISSUE TITLE
Check that new `trait_category` column in study table won't break pipeline

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#108]
I have added a new column (`trait_category` nullable string) to the study table. This will be used by Eliseo for the phewas api.

The modified table is in staging (`gs://genetics-portal-staging/v2d/180913/studies.tsv`).

@mkarmona will need to check that it won't break the v2d pipeline if I copy to genetics-data.

**Comment by mkarmona** [comment]
Included. It will be in the next genetics-pipe run

**Comment by mkarmona** [comment]
It is already included.
