### ISSUE TITLE
Have we got search right yet?

### ISSUE THREAD

**Issue by peatroot** [opentargets/genetics#110]
*If you have an unexpected search result, please paste it below.*
(Ideally indicate what you typed, what you saw and what you expected...)
(...or where you went, what you saw and what you conquered?)

**Comment by elipapa** [comment]
_"If You're Not Embarrassed By The First Version Of Your [search], You’ve Launched Too Late"_

|typed|expected|obtained|
|------|--------|----------|
|"alzh"|alzheimer's disease studies| nothing|
|"alzheimer"|Marioni 2018 study| Seshadri 2010 study|
|"alzheimer's"|Marioni 2018 study|Marioni 2018 study ✅
|"park"|Park7 gene + studies of parkinson|Liver enzyme levels study by Park et al|
|"parkinson's|Chang 2017|Hill-Burns 2014|
|"parkinson|Chang 2017| Beecham 2015|
|"ibd"|KM de Lange 2017|Franke 2007 crohn's study|
|"inflammatory"|KM de Lange 2017|Duerr 2006 ibd gwas (not bad)|

**Comment by MayaGhoussaini** [comment]
`rs9648716` is a triallelic variant. It has two forms `7_140612163_A_T` and `7_140612163_A_G`.
If you search for `7_140612163`, you see both listed (same rsId), but if you search for `rs9648716`, you get `rs9648716*` (quite a long list). Should we boost the exact match for rsid?

**Comment by elipapa** [comment]
a multi word string such as `type 2` returns lots of genes, but the studies/traits are the bottom.

studies should match on `author last name` (exact match, not ngram), `trait` and be sorted by `n_cases` DESC and `year` DESC

**Comment by emschmidt** [comment]
When I search for rs9648716, I get no matches that identify the correct variant. Should the rsID search be an exact match?

**Comment by andrewhercules** [comment]
Just adding comments about search made in the #genetics-platform Slack channel:

edm [11:57 AM]
@channel We need to get the search correct as it doesn’t perform very well at the moment. This is what we think in our office:
- variant ID and rsids should be exact match only
- gene names should be prefix search
- ensembl gene IDs should be exact match
- trait name should allow partial matching (ngrams ?)
- EFO label should allow partial matching (ngrams ?)
- author should allow partial matching (ngrams ?) (edited)
Author names might be more difficult, e.g. authors with short (2 letter) names

**Comment by mkarmona** [comment]
So @MayaGhoussaini if you now type this variant `rs9648716` it returns the two forms of the triallelic variant.

@andrewhercules it meets this at the moment:
- variant only exact match in variant id and rsid
- gene only exact match in gene id, gene name prefix match
- study exact match for pubmed id and study id
- study prefix complete as you type for trait and author and _all fields

@elipapa, @edm1  I think search start returning sensible results. could you please have a look at it to see how it behaves? Thanks

Next iteration is support ngram but I need to reindex everything and configure ngram with it could take a bit. So I will give it another iteration at the end of the next week (week nº 40)

**Comment by edm1** [comment]
I think it is also very important that you are able to search for a trait and an author at the same time. E.g. `neale height` returns nothing.

**Comment by edm1** [comment]
Examples where search doesn't fit our needs:
- `TNF` gives a list of genes matching TNF prefix but not TNF itself
- `neale height` returns no data

**Comment by ElaineMcA** [comment]
Closing as complete for ASHG meeting.  Enhancement ticket will be opened for V2.0 release.
