### ISSUE TITLE
filter insignificant VEP consequences  from gecko API call

### ISSUE THREAD

**Issue by elipapa** [opentargets/genetics#111]
VEP is the only source that can produce a score = 0
We should filter the overall score returned to eliminate variant consequences of little significance, such as `upstream_gene_variant`

**Comment by mkarmona** [comment]
done!.

**Comment by edm1** [comment]
This fix doesn't appear to be working, e.g. https://genetics-app.netlify.com/variant/19_836043_T_C

**Comment by mkarmona** [comment]
@edm1 done it again! But this is a temporal fix. We have to remove all `max_effect == 0` from the v2g and therefore not get included into the intersection table.
