### ISSUE TITLE
Add study's sample size to `studyInfo(studyId)` query

### ISSUE THREAD

**Issue by peatroot** [opentargets/genetics#114]
Motivation: Maya raised that it would be helpful to display each study's sample size on the *studies comparison page* (per row in the table).

Can the `studyInfo(studyId)` query be updated to accommodate this @mkarmona?

**Comment by mkarmona** [comment]
@peatroot @mirandaio, @elipapa and I added the required information. API now delivers a full study info with all possible fields we have in the studies file from pipeline data
```GraphQL
query test4 {
  studyInfo(studyId:"NEALEUKB_20110_8") {
    studyId
    pmid
    traitCode
    traitReported
    traitEfos
    pubDate
    pubJournal
    pubTitle
    pubAuthor
    ancestryInitial
    ancestryReplication
    nInitial
    nReplication
    nCases
    traitCategory
  }
}
```
This study object has been reused across all api calls that return a study object. Internally, it is using fetchers as a [cacheable deferrers](https://www.howtographql.com/graphql-scala/4-deferred_resolvers/).

**Comment by mkarmona** [comment]
@peatroot what is the status of this? this isn't prioritised for October, is it? It is done on my side but not sure if this issue is also linked to you Gareth.
