### ISSUE TITLE
Infographic:  Data Pipeline

### ISSUE THREAD

**Issue by dj-wright** [opentargets/genetics#116]
Create a flowchart/infographic which demonstrates the data flow during the aggregation stage of the portal (everything from data sources throughout to scoring).

Intend this to be an overview on Data Pipeline § Aggregation Stage

I have an approximation, but needs further input from @edm1 and creative input from @andrewhercules

**Comment by peatroot** [comment]
Just a thought on this; it might be nice to tie in the data model schematics we currently have in the site (example below).
<img width="144" alt="screen shot 2018-09-19 at 09 51 38" src="https://user-images.githubusercontent.com/7376272/45742389-c6b40880-bbf1-11e8-8763-5185bbb2c561.png">

**Comment by dj-wright** [comment]
Sounds good.  Really like those as a tool to contextualise what you're looking at
