### ISSUE TITLE
Link out to gnomAD

### ISSUE THREAD

**Issue by elipapa** [opentargets/genetics#12]

**Comment by peatroot** [comment]
To clarify @edm1 @emschmidt @dj-wright, does this mean:
* top of gene page -> `http://gnomad.broadinstitute.org/gene/<geneId>`
* top of variant page -> `http://gnomad.broadinstitute.org/variant/<variantId>` (note form is **1-55516888-G-GA** not **1_55516888_G_GA**)

**Comment by edm1** [comment]
Just to confirm, the above is correct. Once linking to gnomAD, we can stop linking to ExAC.
