### ISSUE TITLE
Gecko table - format?

### ISSUE THREAD

**Issue by peatroot** [opentargets/genetics#120]
Currently, the table under the gecko plot shows **unique S-IV-TV-G associations** with a few other fields.

Other suggestions mooted include:
* **unique TV-G associations**
* **unique S-IV-TV associations**
* all of the above (separate tables in tabs or cards)

Which option should it be? Once the option is picked, are we missing any fields needed?

**Comment by peatroot** [comment]
@MayaGhoussaini @dj-wright @edm1 @emschmidt , can you please think on this and comment below?

**Comment by andrewhercules** [comment]
My recommendation is that we just show the unique `unique S-IV-TV-G associations` for ASHG move this ticket Icebox and look at it for the Genetics 2.0 release. We can start to encourage users to click the respective entities within the table to get to the entity page - so for example, clicking the Tag Variant to visit the variant page where they can see the underlying scores linking that variant to all genes.

**Comment by ElaineMcA** [comment]
Address in aggregation.
