### ISSUE TITLE
Credible set size should never be 0 in Manhattan

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#126]
E.g. https://genetics-app.netlify.com/study/GCST004894

Credible set analysis hasn't been run for studies where we have no summary statistics available.

Rather than returning 0, the API should be returning nothing.

**Comment by mkarmona** [comment]
@peatroot @mirandaio @edm1 either crediblesetsize and ldsetsize now returns null or a number > 0

**Comment by edm1** [comment]
This doesn't appear to be fixed, e.g. https://genetics-app.netlify.com/study/GCST004132

**Comment by mkarmona** [comment]
@edm1 it is fixed in my branch. I will push this out today
