### ISSUE TITLE
Colocalisation analysis

### ISSUE THREAD

**Issue by elipapa** [opentargets/genetics#13]
Conduct and display collocalization with gene/protein expression, other selected traits

**Comment by edm1** [comment]
Steps:

- [ ] Write analysis plan to share with partners / OT coloc working group
- [ ] Prepare data
    - [ ] Add AD GWAX summary stats to GCS sumstat folder (this will be our test dataset)
    - [ ] Add GTEx all pairs to GCS sumstat folder
    - [ ] Create 10k subset of UK Biobank genotypes to use as an LD reference panel

- [ ] Test implementation
    - [ ] Re-write finemapping pipeline using CWL and GCS sumstats so that it can be run automatically as new datasets are added
    - [ ] Create credible set overlap table. Where an overlap exists (>=1 shared credible set variant) between trait and molecular trait, run full coloc analysis.
    - [ ] Implement required API to query sum stats in clickhouse
    - [ ] Write workflow using coloc
    - [ ] Write workflow using Verena's coloc (codename: vloc)

- [ ] Full scale implementation
    - [ ] Create list of studies with EUR ancestry on which we will run coloc
    - [ ] Run workflow

**Comment by edm1** [comment]
Interim solution can be found here: https://github.com/edm1/coloc_interim

**Comment by edm1** [comment]
Idea: try to impute H4/H3 stats from the overlap table, using e.g. features
- log(pval) for A and B lead variant
- A/B distinct and overlapping
- abs(distance between A and B leads)
- rank variants in A and B credible sets, how many overlap in each quartile?

**Comment by edm1** [comment]
New list of steps before complete...

Example results files
- [ ] Produce finemapping output
- [ ] Produce coloc output
- [ ] Filter sumstat files for regional plot development

Data preparation
- [ ] "Ingest" all GWAS Catalog sumstat files (create manifest to only include EUR cohorts)
- [ ] "Ingest" all eQTL DB sumstat files
- [ ] Process GTEx (including liftover to GRCh38)
- [ ] Process Sun et al pQTL (including liftover to GRCh38, and harmonisation)
- [ ] Prepare UK Biobank 10K subset LD reference (including liftover to GRCh38)

Where will the analysis be run?
- [ ] Contact Sanger HPC group
- [ ] Contact UK10K owner about using data on GCS
- [ ] Contact UK Biobank about using data on GCS

Run final analysis
- [ ] Run fine-mapping
- [ ] Run coloc
