### ISSUE TITLE
Create basic gene page

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/genetics#134]
During yesterday's meeting, we discussed two options:

1. Having a separate gene page
2. Adding summary gene data and external links to the top of the Locus View plot page and using JavaScript and conditional logic to only show when user has searched for a gene

To allow for future growth (e.g. exome data that could be available for version 2.0 of the Portal) and to keep the experience consistent across all entities (study, variant), I recommend that we create a separate gene entity page.

The key features would be:

1. HGNC gene symbol
2. Protein name
3. Link to Locus View plot
4. Uniprot description of the gene with PubMed ID hyperlinks to EuropePMC
5. Icons showing what data is available from the Open Targets Platform
6. External links to websites including Ensembl, Uniprot, and ExAC
7. Studies/traits associated with the gene (a replica of the table shown below the Locus View plot)

See below for an initial mockup:

![gene_page_v1](https://user-images.githubusercontent.com/7490258/46076694-3b54ed00-c186-11e8-9151-966d58768703.png)

As an interim solution, I would also recommend that we make use of the Platform API. Based on the data returned by the [/platform/private/target/{target}](http://api.opentargets.io/v3/platform/docs#operation/getTargetByENSGID), perhaps we could also activate/disable the icons showing the data available from the Open Targets Platform based on the length of their respective arrays?

**Comment by elipapa** [comment]
how about building an icon for the "locus view" ? 
would also help branding.

**Comment by andrewhercules** [comment]
Here's the updated layout of the gene page that does not require a REST call to the Open Targets Platform API. All of the icon links can be hardcoded to direct users to the relevant the target profile page section. 

![gene_page__associated_studies_tab_open_](https://user-images.githubusercontent.com/7490258/46204520-6883d580-c315-11e8-9027-0e24cf73588e.png)

**Comment by andrewhercules** [comment]
@elipapa, good point about the icon. In the mockup above, I used a white version of this icon - what do you think?

![locus-view-icon-colour-sm](https://user-images.githubusercontent.com/7490258/46204586-ae409e00-c315-11e8-9585-7e192dd2b60e.png)

**Comment by andrewhercules** [comment]
I've updated the mockup for the gene page based on feedback - see below. If the blue for the static link icons is too much, we can also make them in grey (#5a5f5f). SVGs of the icons can be found on the [team's Google Drive](https://drive.google.com/open?id=1V0-jPRrM7y_Ejqp2gj93DdVnz3eNq6LF). Also, for the "Other Links" section, I included links to platforms/portals that only require either a HGNC symbol or Ensembl ID. If there are other resources I have forgotten, please feel free to include them.

![gene_page_with_associated_studies_table](https://user-images.githubusercontent.com/7490258/46410267-217c5280-c710-11e8-9b5e-973584920f17.png)

**Comment by deniseOme** [comment]
Please capitalise P for "prot" in UniProt.

What is the rationale of linking out to Gene Cards, HGNC and all those resources?

I personally would keep the linksouts to a minimum. It may be distracting, it makes the page busier than it should be. 

Do we really need to link out to Ensembl and Gene Cards? Neither is willing to link out to us.
What do those resources provide at their gene pages that we don't?
What is the benefit for the user?

I'd have linked out to the Open Targets Platform target profile page and voila'! That page is a 'cv' of the gene and links out to UniProt, Ensembl and plenty more. The target profile page does not link out to HGNC, this has been raised by HGNC in the past. Perhaps we should create an issue in Platform to revisit this.

**Comment by andrewhercules** [comment]
Good spot - thank you. I've updated the mockup - see below.

We are including external links in an effort to replicate some of the functionality found on other popular genetics websites and to minimise the need to click through to the Platform in order to get to Ensembl, UniProt, etc. For example, on the [ExAC](http://exac.broadinstitute.org/gene/ENSG00000169174) and [Varsome](https://varsome.com/gene/BRAF) website, they have a variety of external links for supplementary information. On our site, these links would be a lighter grey so they aren't as noticeable on first glance.

Moving forward, we shouldn't make including external links contingent on whether those resources link back to the Platform or the Genetics Portal. [Linkbacks](https://en.wikipedia.org/wiki/Linkback) are great, but we should be focussed on giving our users the right mix of external links and contextual information as this helps with SEO (we get seen as an authority on a topic).

**Comment by andrewhercules** [comment]
When looking at the gene page on a laptop (Macbook Air, 14-inch, 2014 model), the icons take up two lines - see below for a screenshot. Can we either fix the icon sizes so they are one line or drop a link (the mouse phenotype or pathway icon)? Also, can the links please open in a separate tab?

![screen shot 2018-10-10 at 10 35 38 pm](https://user-images.githubusercontent.com/7490258/46777406-5d4d8400-ccdd-11e8-893a-3fa960d19a49.png)

**Comment by mirandaio** [comment]
@andrewhercules fixed.
