### ISSUE TITLE
Blank Study Page

### ISSUE THREAD

**Issue by emschmidt** [opentargets/genetics#138]
Study page is blank when I search for the following study:
https://genetics-app.netlify.com/study/GCST005837

One possible reason is that it is flagged as a 'targeted or exome array study' in GWAS catalog.

**Comment by emschmidt** [comment]
It does work as expected for other 'targeted' studies, though. For example:
https://genetics-app.netlify.com/study/GCST005550

**Comment by peatroot** [comment]
Two solutions spring to mind about this:
1. show a message saying we have no data
2. filter studies with this property out of the search results (then there's no way get to the page)

I think option 2 makes more sense. @mkarmona @edm1 @emschmidt, thoughts?

**Comment by mkarmona** [comment]
I think we should prepare a nice 404 page saying no data but with sensible
alternative resources as results from our search endpoint suggesting
silimsr studies or so. not having doesn't mean we can't keep engaging our
(future) users.

**Comment by emschmidt** [comment]
Here is an example of a blank 'no association' study page from Neale UK Biobank: https://genetics-app.netlify.com/study/NEALEUKB_20002_1454

**Comment by peatroot** [comment]
Recently added handling means that users now see at least a **(no data)** message instead of an empty screen.

**Comment by edm1** [comment]
There is currently no LD or finemapping data for GCST004132. This will change with the most recent run of the pipeline.

However, navigating to the comparison page gives a blank screen: https://genetics-app.netlify.com/study-comparison/GCST004132

Is it possible to have a (no data) message here too?

**Comment by peatroot** [comment]
Added handling for cases like GCST004132 (https://github.com/opentargets/genetics-app/commit/b73cba76a43956670807ed8eb4b8ced29d969823).
