### ISSUE TITLE
Gecko plot - fix mouse interaction in safari

### ISSUE THREAD

**Issue by peatroot** [opentargets/genetics#139]
Currently, the Gecko plot does not support mouse interaction in Safari 12.0, but this is supported in Chrome and Firefox.

**Comment by ElaineMcA** [comment]
Recommend users to use appropriate browsers to allow time for investigation.

**Comment by ElaineMcA** [comment]
Updating to icebox for moment until use cases for locus plot are generated by @MayaGhoussaini for discussion -  we can then revisit if a more extensive redesign is needed.

**Comment by ElaineMcA** [comment]
Affects small # of users and difficult to resolve based on review with @peatroot.
