### ISSUE TITLE
Add V2G display labels to API

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#142]
I have added display labels to `gs://genetics-portal-data/lut/v2g_display_labels.json`. These need to be served to the front-end.

**Comment by peatroot** [comment]
We've hacked this on the front-end for ASHG. The extra fields (with names `sourceLabel`, `sourceDescriptionOverview`, `sourceDescriptionBreakdown` and `pmid`) are added to type `GenesForVariantSchema` in this script https://github.com/opentargets/genetics-app/blob/master/src/logic/transformGenesForVariantSchema.js.

**Comment by mkarmona** [comment]
@edm1 this is missing the _distance_ v2g type.

**Comment by mkarmona** [comment]
@peatroot I already updated the API to contain the required fields you mentioned. most of them come with all the information you need to stop hacking the frontend.
```GraphQL
query asdf {
  genesForVariantSchema {
    qtls {
      id
      sourceId
      displayLabel
      overviewTooltip
      tabSubtitle
      pmId
      tissues {
        id
        name
      }
    }
    intervals {
      id
      sourceId
      displayLabel
      overviewTooltip
      tabSubtitle
      pmId
      tissues {
        id
        name
      }
    }
    functionalPredictions {
      id
      sourceId
      displayLabel
      overviewTooltip
      tabSubtitle
      pmId
      tissues {
        id
        name
      }
    }
    distances {
      id
      sourceId
      displayLabel
      overviewTooltip
      tabSubtitle
      pmId
      tissues {
        id
        name
      }
    }
  }
}
``` 
@edm1 can you add the remaining description for `distance` dataset? Please mind those fileds can be nullable so is fine having nothing when it is appropiate.
