### ISSUE TITLE
locus window does not treat errors as they come from the `graphql` API query

### ISSUE THREAD

**Issue by mkarmona** [opentargets/genetics#144]
![captura de pantalla -2018-09-28 09-42-12](https://user-images.githubusercontent.com/5394232/46197936-189c1300-c303-11e8-9496-983bae12911d.png)

As the locus window gets wider API stops replying with data but throughing an error as the locus length is `> 2Mb`. I also have to specify that limit in the error message.

**Comment by peatroot** [comment]
Does now.
