### ISSUE TITLE
Home page - I'm feeling lucky

### ISSUE THREAD

**Issue by peatroot** [opentargets/genetics#151]
When a user arrives at the homepage, it'd be nice to have:
* fixed examples (could be one of each below, or we could have a new one every day?)
  * an example gene
  * an example variant
  * an example study
* **I'm feeling lucky** - this could pick randomly from a list of urls (so users could arrive at study comparison and locus pages)

@MayaGhoussaini @edm1 @emschmidt @dj-wright, can you paste your favourite examples of genes, variants and studies below? Also, if you know/find any interesting cases of locus view and/or study comparison view, please paste the urls below?

**Comment by emschmidt** [comment]
Some initial suggestions:
PCSK9: https://genetics-app.netlify.com/gene/ENSG00000169174
1_154426264_C_T: https://genetics-app.netlify.com/variant/1_154426264_C_T
Atrial fibrillation (Roselli C et al. 2018): https://genetics-app.netlify.com/study/GCST006061

Also, can we please remove 'This platform uses GRCh37 from the Genome Reference Consortium' from the homepage? This info is included in the documentation.

**Comment by peatroot** [comment]
Great, thanks. Yes, ok, I'll remove that message.
