### ISSUE TITLE
Study comparison page - overlapping indices table

### ISSUE THREAD

**Issue by peatroot** [opentargets/genetics#153]
Below the table showing flattened Manhattan plots, we should add a table that contains the index variants from the root study, such that they are in the intersection with all other studies.

This table should be similar to the Manhattan table on the study page, but should also contain a link to the locus  page, such that the locus is centred on the index variant with the chosen studies selected.

**Comment by edm1** [comment]
This should contain columns [Lead variant, rsID, Cytoband, Top Ranked Genes, View] from the Manhattan API querying using studyA. Only show variants that are in intersection set.

"Lead variant" to be renamed "Variant", with tooltip "The locus tagged by this variant is shared across all selected studies".

View will go to the Locus plot with all selected studies selected.
