### ISSUE TITLE
Gene page - associated studies table

### ISSUE THREAD

**Issue by peatroot** [opentargets/genetics#155]
## Design
| StudyId | Details | View |
| -- | -- | -- |
| NEALEUKB_20015 | Sitting height (...) | Locus (button) |

## Proposed API schema
```
type query {
  studiesForGene(geneId: String!) [StudyForGene!]!
}
type StudyForGene {
  study: Study!
  // nothing else for now, but likely to have a combined score in future (aggregating g2v + v2d scores)
}
```

**Comment by mkarmona** [comment]
@peatroot I implemented this query as you defined. It will be deployed by Monday morning.
