### ISSUE TITLE
PheWAS table - Inconsistent/missing data

### ISSUE THREAD

**Issue by MayaGhoussaini** [opentargets/genetics#157]
The data in this table  refer to UK Biobank. Note that: 

'N cases' is showing nothing 
'N_Overall'  has values between a couple of thousands  to hundreds of thousands

**Comment by edm1** [comment]
Can you post an example link. I agree `N cases` should not be missing (the information is present in the study table). However, as far as I can tell `N_Overall` is correct.

**Comment by ElaineMcA** [comment]
@edm1 to investigate.
