### ISSUE TITLE
Filter studies flagged as "targeted or exome array" in GWAS from search results

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/genetics#163]
Study page is blank when I search for the following study:
https://genetics-app.netlify.com/study/GCST005837

One possible reason is that it is flagged as a 'targeted or exome array study' in GWAS catalog.

A longer-term enhancement post Oct2018 is to filter studies with this property out of search results (this would mean that there is no way to get to this page).

(Short-term fix addressed via https://github.com/opentargets/genetics/issues/138 for ASHG meeting)

**Comment by edm1** [comment]
This occurs when the study was curated by GWAS Catalog but no associations we recorded (so the study is in the study table but not the top loci table).
