### ISSUE TITLE
Trait category label is ID10 instead of ICD10

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/genetics#166]
Hello, 
I was looking at the PheWAS plot and the orange category is ID10 instead of ICD10.
Can this be corrected please?

**Comment by edm1** [comment]
This is coming from the source file `gsutil cat gs://uk_biobank_data/em21/neale_summary_statistics_20170915/PheWAS_categories/neale_cateogries.tsv | grep ID10 | head` and will have to be fixed in a future run of the pipeline (post-October).

**Comment by edm1** [comment]
Fixed here: https://github.com/opentargets/v2d_data/commit/ba21756fcf27cf732ff96e3a74a5f9639178e7ba

Will be fixed in the portal when the genetics-pipe is next run.
