### ISSUE TITLE
Update the footer to match the footer used in the Platform

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/genetics#169]
Currently, the footer of the Genetics Portal looks like this:

![screen shot 2018-10-01 at 15 08 58](https://user-images.githubusercontent.com/7490258/46293663-10a2d400-c58c-11e8-929e-4637df4c8774.png)

However, David has asked that we use the footer found in the Platform to ensure consistency: 

![screen shot 2018-10-01 at 15 09 17](https://user-images.githubusercontent.com/7490258/46293695-2adcb200-c58c-11e8-8772-00b3b518c684.png)

**Comment by MayaGhoussaini** [comment]
Sounds good Andrew.
We just need to change the support email under ‘Help’.
Best,
Maya


--
Maya Ghoussaini, PhD
Genetic Analysis Team Leader
Open Targets, Wellcome Trust Sanger Institute
Hinxton, Cambridge CB10 1SD, UK
Tel: +44 (0) 1223494378
Email: mg29@sanger.ac.uk<mailto:hf6@sanger.ac.uk>

**Comment by andrewhercules** [comment]
Thanks @MayaGhoussaini - good point. @mirandaio and @peatroot, can we please make sure that the email address is geneticsportal@opentargets.org? :-)

**Comment by mirandaio** [comment]
@andrewhercules @MayaGhoussaini yep 👍

**Comment by deniseOme** [comment]
Minor discrepancies can still be observed:

Portal: ("Connect with us", order of the social media icons - Facebook first-, and order of partners: alphabetical)
<img width="854" alt="screen shot 2018-10-05 at 11 22 50" src="https://user-images.githubusercontent.com/6472381/46530257-10a71a80-c891-11e8-8f30-c4f76da9c865.png">

Platform: ("Follow us", order of the social media icons, - LinkedIn first-, and order of partners: Celgene last)
<img width="949" alt="screen shot 2018-10-05 at 11 22 57" src="https://user-images.githubusercontent.com/6472381/46530264-156bce80-c891-11e8-8a76-54a5ee8339bd.png">

So we'd need to choose: 
* "Connect with us" or "Follow us" (I'd recommend "Follow us" as in the Platform we have the "Follow us" at the side of the pages as well
![Uploading Screen Shot 2018-10-05 at 11.30.18.png…]()

* The social media icon order (I have no preference)

* The partner names' order (I'd recommend alphabetical. So Platform needs changing. Perhaps one for @LucaFumis?)

**Comment by andrewhercules** [comment]
For the ASHG release, this is being marked as done and closed. The discrepancies are minor enough that they don't impact overall functionality. 

There will be another ticket opened where we can put polish-related issues and then prioritise from that - will be discussed during Monday's meeting.

And in terms of changes to the Platform footer, I have recommended to the team that we rebuild the footer for both the Platform and Portal as part of a broader re-branding and component building exercise.

**Comment by deniseOme** [comment]
Thanks a lot @andrewhercules for your comments. Much appreciated. Great to know there will be a broader re-branding and component building exercise sometime soon.

I think footer in general does not impact the functionality of any website, let alone the Genetics Portal or the Open Targets Platform. 

I have noticed from workshops on the Platform that people don't really seem to pay attention on footers, they don't even know there are important info there such as release notes.

The original ticket was about consistency. My suggestions as stated in the reopened ticked were minor, but nevertheless still consistency related.
