### ISSUE TITLE
Investigate why overlapping locus from Compare Studies page doesn't overlap in Locus View

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#183]
Looking at GCST006061 | NEALEUKB_102 on the Compare Studies page (https://genetics-app.netlify.com/study-comparison/GCST006061?studyIds=NEALEUKB_102)

If we navigate to the Locus View for the first row in the intersection table (https://genetics-app.netlify.com/locus?chromosome=2&end=180411665&selectedStudies=GCST006061&selectedStudies=NEALEUKB_102&start=178411665)

There is overlap in the overlap table, but not in the Locus View

**Comment by edm1** [comment]
Looking at the raw input data
```
# Trait A tag variants
('GCST006061', '2_179411665_A_G') = {'2_179381715_G_C', '2_179389742_G_C', '2_179411665_A_G', '2_179414633_C_A', '2_179421294_C_T', '2_179430997_G_A', '2_179444137_A_G', '2_179444939_C_T', '2_179448911_G_A', '2_179489726_A_G', '2_179490478_T_C', '2_179490954_C_T', '2_179515774_A_G', '2_179533609_A_C', '2_179541612_C_T', '2_179543217_C_T', '2_179547860_A_G', '2_179551083_G_A', '2_179562140_T_C'}

# Trait B tag variants
('NEALEUKB_102', '2_179388490_G_A') = {'2_179388490_G_A', '2_179403593_G_A', '2_179388657_G_A', '2_179382809_T_G', '2_179388994_A_G', '2_179405885_T_C', '2_179404786_A_T', '2_179386240_A_G', '2_179514433_T_C', '2_179380165_A_G', '2_179413110_G_A', '2_179396354_G_A', '2_179397561_C_T', '2_179380096_A_G', '2_179406191_C_T', '2_179421470_T_G', '2_179398823_G_A', '2_179436020_G_A', '2_179392080_A_T', '2_179421294_C_T', '2_179381715_G_C', '2_179457147_G_A', '2_179595117_C_G', '2_179458591_C_T'}

# Intersection
{'2_179381715_G_C', '2_179421294_C_T'}
```
We expect these two tag variants to be shared in the Locus View.

**Comment by mkarmona** [comment]
@edm1 could it be because those don't have functional data so intersection table miss them and therefore there is no gecko to show

**Comment by edm1** [comment]
Both '2_179381715_G_C' and '2_179421294_C_T' have V2D data.

The index variant for the Neale study 2_179388490_G_A has no tag variants on the variant page (https://genetics-app.netlify.com/variant/2_179388490_G_A).

Also, if you go to the Locus View for the same variant (https://genetics-app.netlify.com/locus?chromosome=2&end=180388490&selectedTagVariants=2_179388490_G_A&start=178388490), it is not connected to NEALEUKB_102.

It appears that the fine-mapping data connecting ('NEALEUKB_102', '2_179388490_G_A') to the tags is not present.

**Comment by edm1** [comment]
The bug is coming from my end.

The top loci table is made from a filtered version of the finemapping table, which is correct.

However, I'm using the full (unfiltered) finemapping table to calculate overlaps. So the overlap table contains (stid, index_var) pairs that are not in the top loci table.

I will fix the overlap table now.

**Comment by edm1** [comment]
Fixed by https://github.com/opentargets/v2d_data/commit/7dacaa84b39ae24800e0df10480b849957b6820c.

The fixed overlap table has been copied to `gs://genetics-portal-data/v2d/locus_overlap.json.gz`. @mkarmona will need to load the fixed data to clickhouse.
