### ISSUE TITLE
Enhance existing search bar function

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/genetics#185]
Put in a regex for exactly that format, but I'd be in favour of just supporting the format CHROMOSOME_POSITION_REFALLELE_ALTALLELE. There's an example on the homepage and as you said, ExAC uses the format CHROMOSOME-POSITION-REFALLELE-ALTALLELE.

If it's necessary, @mkarmona should be able to match this on the backend.

**Comment by mkarmona** [comment]
We now support CHROM-POS-REF-ALT and CHROM:POS:REF:ALT
