### ISSUE TITLE
Feedback and Follow us buttons at the side of the homepage

### ISSUE THREAD

**Issue by deniseOme** [opentargets/genetics#189]
Will we keep with the theme of the Platform, and place a "Feedback" and "Follow us" button on the homepage and "Feedback" throughout the Genetics Portal (i.e. Homepage and elsewhere)?

<img width="205" alt="screen shot 2018-10-05 at 11 41 15" src="https://user-images.githubusercontent.com/6472381/46531082-d9863880-c893-11e8-8e80-f4c03b8e8069.png">
<img width="305" alt="screen shot 2018-10-05 at 11 42 58" src="https://user-images.githubusercontent.com/6472381/46531084-d9863880-c893-11e8-86d4-f5e1efeabc85.png">

The "Feedback" would be linked to mailto:geneticsportal@opentargets.org and if users click on it from any page where they need help, the support email will include the exact page the user had issues with.

**Comment by ElaineMcA** [comment]
Closing - will be addressed with future rebrand.
