### ISSUE TITLE
Update layout of homepage

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/genetics#197]
How does this work as a homepage? I can make the hexagon images and text into SVGs.

![genetics_portal_homepage_v1](https://user-images.githubusercontent.com/7490258/46539638-f5e39e80-c8ae-11e8-9f4a-cb84dc513347.png)

**Comment by andrewhercules** [comment]
@peatroot and @mirandaio, here are the design assets for the homepage:

* [3 features of Portal hexagons](https://drive.google.com/open?id=1XEIurWHeba-FK3efbiu4oXbMH8hqxir4)
* [Portal journey steps](https://drive.google.com/open?id=1JpHlT2uqCH4o8VTxLGnMFzx2gGSXqvJ6)
* [Open Targets Genetics logo in SVG format](https://drive.google.com/file/d/1G00sKSYSOBTIWUOwq5ksn5EJ5LNnZK7b/view?usp=sharing)

Also, so that the homepage will look better on a large screen in the auditorium early on Thursday morning, can we please:
- [ ] Change the background colour to the blue #3489ca
- [ ] Remove the gradient (so that it's a flat colour)
- [ ] Make the white lines softer, perhaps by adding an opacity of 0.2 to 0.4? 

@MayaGhoussaini, can you please review the content of the homepage sections to make sure it is correct from a scientific standpoint - you know how I can get with #AndrewsTargets! haha :-)

Specifically, I thought that you may want to change the tagline "Explore gene-variant-trait associations from UK Biobank and GWAS Catalog" as I just used that as a placeholder.

**Comment by mirandaio** [comment]
Hi @andrewhercules, thanks for the design and assets. Could you polish the Portal journey steps asset a little bit? I've marked the parts that can be improved. Thanks!

![asset](https://user-images.githubusercontent.com/1652699/46861651-06de6380-ce0b-11e8-83ed-1b347f2d77bd.png)

**Comment by edm1** [comment]
Looks great. Only comment is that "Gene2Variant (g2v)" should be "Variant-to-Gene (V2G)". This is in the text and in the figure.

**Comment by edm1** [comment]
Also, in when saying what we can search by, I don't think we need to say HGNC symbol / Ensembl ID / RSID etc. It could just be "You can search by gene, variant or study (trait, author, or by trait AND author)".

Although, we currently can't search by trait AND author!

**Comment by andrewhercules** [comment]
@mirandaio, thanks for catching those errors. I've updated all of the assets:

- [3 features of Portal hexagons](https://drive.google.com/open?id=1XEIurWHeba-FK3efbiu4oXbMH8hqxir4)
- [Portal journey steps](https://drive.google.com/open?id=1JpHlT2uqCH4o8VTxLGnMFzx2gGSXqvJ6)
- [Open Targets Genetics logo in SVG format](https://drive.google.com/file/d/1G00sKSYSOBTIWUOwq5ksn5EJ5LNnZK7b/view?usp=sharing)

I've also created a [white version of the logo](https://drive.google.com/open?id=1Uk4c4dQCvFmq412dBz-tbL9yq5DLdwbr) in case you want to use it in the header.
