### ISSUE TITLE
Locus View plot not showing data

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/genetics#209]
When the Locus View plot has too much data to show, the user is presented with an error message, "Ouch! The region '(19:44412079-46412079)' is too dense to be shown." Ideally, the error message should communicate that a user needs to remove one or more entities in order to see the evidence and links. So for example, "The region '(19:44412079-46412079)' is too dense to be shown. Please remove one or more entities to see the evidence within the region".

But I have noticed that removing entities or changing the zoom still does not allow data to be shown (eg. https://genetics.opentargets.org/locus?chromosome=19&displayFinemapping=1&displayType=1&end=46412079&selectedIndexVariants=19_45412079_C_T&start=44412079). 

![screen shot 2018-10-10 at 10 45 25 pm](https://user-images.githubusercontent.com/7490258/46779113-802f6680-cce4-11e8-95ba-e1947af5e7f3.png)

**Comment by peatroot** [comment]
That's because filtering is currently done on the front-end and the error is regardless of the zoom level. To do otherwise would require substantial API changes.

**Comment by andrewhercules** [comment]
Okay, but even when I've zoomed in all the way, there's still too much data to show?

https://genetics.opentargets.org/locus?chromosome=19&displayFinemapping=1&displayType=1&end=45412081&selectedIndexVariants=19_45412079_C_T&start=45412077

If so, we either need to make changes to the API or return some kind of status that will disable links to a Locus View that dense.

**Comment by andrewhercules** [comment]
Also, could we put a Google Event on the Locus View plot when the "too dense" error shows?

**Comment by peatroot** [comment]
The API checks whether your `(chromosome, start, end)` touches any one of a set of too dense regions. If so, you get the message.

**Comment by peatroot** [comment]
We could, but Miguel can tell you how frequently his API errors. Also, 25 of 1,561 2MB windows are too dense (see https://github.com/opentargets/genetics/issues/176). Ultimately, we need to think about aggregating across tag variants.
