### ISSUE TITLE
Neale et al 2017 has no PubMed ID

### ISSUE THREAD

**Issue by peatroot** [opentargets/genetics#213]
A user raised (Integration Day, 11/10/18) that linking to the site/preprint might be useful instead. Should we add this as a special case in the front-end, @edm1?

**Comment by edm1** [comment]
There is no pre-print for Neale et al. The relevant site for the study is http://www.nealelab.is/uk-biobank. It would be useful to link to it if possible.

**Comment by edm1** [comment]
@peatroot What do you think the best solution for this is?

I can add a URL column (in addition to the pubmedid column) to the study file?

**Comment by ElaineMcA** [comment]
Decision: Hardcode link above from frontend.  No action for @edm1.
