### ISSUE TITLE
Is it correct to give 5' & 3'UTR consequences weight of 0?

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#214]
They current are weighted 0. It was suggested on integration day that they should weight non-zero.

**Comment by ElaineMcA** [comment]
No action here for Genetics portal for moment.  @MayaGhoussaini to discuss with relevant stakeholders.

**Comment by edm1** [comment]
@MayaGhoussaini We should decide on new scores before release 2.0.

**Comment by edm1** [comment]
New have been updated
