### ISSUE TITLE
Stats for Open Access week campaign

### ISSUE THREAD

**Issue by deniseOme** [opentargets/genetics#220]
This week is OA week and we can have a few tweets on the theme for both Open Targets Genetics and Platform.

If you had some stats on the data in Open Targets Genetics I could write a tweet like:

`**Q**: Where can you find ??? million variants, ??? thousand human genes, ??? traits, ??? eQTLs, and ??? pQTLs that are #openaccess in the #OAweek & every other week? **A**: Open Targets Genetics: https://genetics.opentargets.org/`

It'd be nice to fill in the blanks in the tweet, but other stats that you think are relevant too would be welcomed :) 

The stats for the Open Targets Platform that we are interested in usually are:
1) number of targets
2) number of diseases
3) number of evidence strings
4) number of associations 

It's very easy with the Platform to get the stats based on this API call:
https://api.opentargets.io/v3/platform/public/utils/stats

(useful for dissemination of our tools and what they provide, or a based on).

**Comment by edm1** [comment]
Sorry, we missed this. We should look to add such stats to the API in the future.

**Comment by edm1** [comment]
Updated queries using big query

```sql
# 19,922 protein-coding genes linked to 9,096 GWAS studies
SELECT
  COUNT(DISTINCT(study_id)),
  COUNT(DISTINCT(gene_id))
FROM
  `open-targets-genetics.190303.disease2variant2gene`
JOIN
  `open-targets-genetics.190303.genes`
USING
  (gene_id)
WHERE
  biotype = "protein_coding"

# 299,463,830 evidence strings linking disease to genes
SELECT
  COUNT(*)
FROM
  `open-targets-genetics.190303.disease2variant2gene`

# 140,799,9517 evidence strings linking variants to genes
SELECT
  COUNT(*)
FROM
  `open-targets-genetics.190303.variant2gene`

# 99,562 GWAS disease-associated loci from GWAS Catalog and UK Biobank
SELECT
  COUNT(*)
FROM (
  SELECT
    DISTINCT study_id,
    lead_chrom,
    lead_pos,
    lead_ref,
    lead_alt
  FROM
    `open-targets-genetics.190303.variant2disease`)

```
