### ISSUE TITLE
improve visibility on narrow screens

### ISSUE THREAD

**Issue by elipapa** [opentargets/genetics#221]
The current layout of the portal does not lend itself well to resolutions below < 1400 px horizontally. 
It is very hard to browse on non-iOS mobile devices or to share it on social media (where recommended horiz resolution for gif and pictures  is ~1200px).

**Comment by ElaineMcA** [comment]
@andrewhercules - Can you please comment based on analytics and proposed view on narrow screen?

**Comment by andrewhercules** [comment]
Closing this issue as it will be addressed when we explore use cases for the locus plot and make improvements to the readability/usability of data tables - see #201 for more information
