### ISSUE TITLE
Issues when setting up instance locally

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/genetics#224]
I want to try to setup an instance locally, but there are some issues that are blocking this now:
- documentation and configuration in [V2G](https://github.com/opentargets/v2g_data), [V2D](https://github.com/opentargets/v2d_data) and [genetics-pipe](https://github.com/opentargets/genetics-pipe) refer to various *gs://* (Google storage) locations which are not accessible to me. Afaik there are no alternative data locations documented.
- if I understand correctly, genetics-pipe will generate output in JSON format. However, I could not find any documentation on how to get from this to a fully loaded ClickHouse DB which is needed by [genetics-api](https://github.com/opentargets/genetics-api).

**Comment by pieterlukasse** [comment]
Notify: @mkarmona

**Comment by mkarmona** [comment]
@pieterlukasse I am actively working on it so bear with me.

**Comment by Sjoerd-van-Hagen** [comment]
@mkarmona Hi Miguel, has any progress been made here? The gs-locations are still not accessible.

Anything else I need to be aware of before trying to set this up?

**Comment by ElaineMcA** [comment]
Closing ticket as will be addressed via F2F training planned for 03Oct2019 and also other more recent ticket requests e.g. #376
