### ISSUE TITLE
pheWAS data and machine optimisation

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/genetics#230]
Objective: pheWAS machine size reasonable.

- [ ] Infrastructure: review machine management

- [ ]  clean the pheWAS data

**Comment by mkarmona** [comment]
@edm1 would you mind pasting on here the equation you want to get the _significance_ ?

**Comment by edm1** [comment]
We're just doing a Bonferroni correction for this, which is 0.05 / (number of tests).

We're currently using "number of traits return by the API" as the number of tests.

Since we won't be returning all traits to the UI, it may be better to use the "total number of traits in the sumstat table".

**Comment by ElaineMcA** [comment]
Under discussion with James @ GWAS team.
