### ISSUE TITLE
Locus-to-Gene (L2G) scoring

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/genetics#231]
**Part 1: Basic L2G score using weighted-average across tags https://github.com/opentargets/genetics/issues/252**

**Part 2: Add coloc evidence https://github.com/opentargets/genetics/issues/253**

**Part 3: Use variant-annotations to weight variants https://github.com/opentargets/genetics/issues/254**

**Comment by edm1** [comment]
Copied the below from #233 

![47718907-88bef100-dc41-11e8-8002-921e6bac4146](https://user-images.githubusercontent.com/1938268/48137259-94419600-e299-11e8-99f5-f7165ced7e57.JPG)

**Comment by edm1** [comment]
L2G scoring tickets have been moved to their own release in zenhub
