### ISSUE TITLE
Scoring: Computation on the fly

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/genetics#233]
Goal: Be able to compute on the fly based on particular customisation per user.

- [ ] Discuss with Ed how and what requirements are

**Comment by ElaineMcA** [comment]
Recommendations discussed with @iandunham 30Oct2018:


![img_3161](https://user-images.githubusercontent.com/40168275/47718907-88bef100-dc41-11e8-8002-921e6bac4146.JPG)

**Comment by iandunham** [comment]
Note the score as written doesn't represent anything on the diagram as there is no path L2, F2 to gene C. But imagine there was one!

**Comment by edm1** [comment]
Discussion of L2G scoring should be moved to https://github.com/opentargets/genetics/issues/231.

This ticket is for computing scores on the fly, which I think is an independent issue.

**Comment by edm1** [comment]
For the time being, we don't have plans to compute on-the-fly.
