### ISSUE TITLE
Locus-Trait Page

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#238]
This page will display information specific to a single Locus (index variant) + Study. There are a number of sections that could be displayed on this page.

**Section 1: Locus-to-Gene scoring results**

https://github.com/opentargets/genetics/issues/246

**Section 2: Colocalisation results**

https://github.com/opentargets/genetics/issues/247

**Section 3: Advanced fine-mapping visualisation**

https://github.com/opentargets/genetics/issues/248

**Comment by ElaineMcA** [comment]
@edm1 Can you please review the current user journey and update where/ how this new page fits into it... so we can define linkages to and from this page as needed early in the process.

- Clarity for me early on.  Thanks!

**Comment by edm1** [comment]
Anywhere that a (study_id, lead_variant) are fixed should link to this page. I.e. Manhattan table, "GWAS lead variants" table on the variant page, Locus plot table.

Also, we could move the "Tag variant" table from the Variant page to the Locus-Trait page.
