### ISSUE TITLE
Display L2G scoring results in front end

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#246]
Similar to V2G table at the top of the variant page, except shows the Locus-to-Gene (L2G) score. Rows are genes, columns are tag variants, additional column is "Overall L2G score".

Depends on:
- Calculation of L2G scores https://github.com/opentargets/genetics/issues/231

**Comment by edm1** [comment]
First draft of layout:

![img_20181112_125811](https://user-images.githubusercontent.com/1938268/48349093-21f6fa00-e67b-11e8-89ac-c35ca66e3618.jpg)

**Comment by andrewhercules** [comment]
After Friday's meeting and a follow-up conversation with the Genetics team, I've started to compile my notes for this page and data table. You can find them on [the team's Google Drive](https://drive.google.com/open?id=1RtLkcdrBD13PWT7YXrTA8TMXeJEtx_Ho4hiBRPXc3uo).

**Comment by peatroot** [comment]
Seems reasonable @edm1. What's the maximum number of columns we'd get? Similarly, the average?

**Comment by ElaineMcA** [comment]
Moved to release 3.0.  Required as prerequisite to exporting summary data to targetvalidation.org.
