### ISSUE TITLE
Locus-Trait Page: (Part 2) Colocalisation results

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#247]
Undecided exactly how these will be displayed.

Depends on:
- New coloc pipeline https://github.com/opentargets/genetics/issues/13 https://github.com/opentargets/genetics/issues/232

However, we do have results of an interim coloc analysis I did pre-ASHG which could be used if we decided to.

**Comment by edm1** [comment]
Rough mock-up:

![img_20181112_125845](https://user-images.githubusercontent.com/1938268/48349127-405cf580-e67b-11e8-9d91-8cf803f5da38.jpg)

**Comment by peatroot** [comment]
@edm1 @mkarmona, will the summary stats table changes described in https://github.com/opentargets/genetics/issues/286 include all values for eQTLs/pQTLs, or only the significant values. If we include all values, the regional plots for studies/eQTLs/pQTLs will be complete. If not, the eQTL/pQTL regional plots will be sparse.

There are approximately 2000 studies, but (gene, tissue) combinations will be much larger, say 20000 genes x 50 tissues at a minimum? [GTEx download](https://gtexportal.org/home/datasets) for all values, including non-significant, is 188GB. For significant only, it is less than 1GB.

The current V2G table only has significant eQTL values.
