### ISSUE TITLE
 Locus-to-Gene (L2G) scoring: (Part 1) Basic implementation

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#252]
Basic L2G score using weighted-average across tags. Doesn't require any new data.

**Comment by edm1** [comment]
Copied from https://github.com/opentargets/genetics/issues/233

![47718907-88bef100-dc41-11e8-8002-921e6bac4146](https://user-images.githubusercontent.com/1938268/48197533-e8a64d80-e34d-11e8-998c-f8a6418c4280.JPG)

**Comment by edm1** [comment]
@mkarmona, I had a quick discussion with @iandunham about the scoring, and I have a better idea of what we should be aiming for.

It is similar to what we discuss previously, except we will need to scale the current V2G scores so that they sum to 1.

I will create a prototype, which should make things easier.

**Comment by edm1** [comment]
Latest versions of the proposed L2G scoring systems:

https://drive.google.com/open?id=1Uzwq6PJMU9o--Xb3JBYQHIaZrpFFCK4a

**Comment by mkarmona** [comment]
@edm1 this is already implemented `version 2` on the click-house side. Do we want to close this and create a new one for next steps?

**Comment by edm1** [comment]
L2G scoring tickets have been moved to their own release in zenhub
