### ISSUE TITLE
Change filename for CSV table downloads on gene page

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/genetics#258]
### Observed Behaviour

When a user downloads a table on the gene page (e.g. [PCSK9](https://genetics.opentargets.org/gene/ENSG00000169174)), the downloaded file name is `undefined.csv`.

### Expected behaviour

When a user downloads a table from the gene page, the filename should contain the HGNC symbol. Perhaps the filename could be `ESR1_associated_studies.csv`?

**Comment by mirandaio** [comment]
@andrewhercules @edm1 should be fixed now.
