### ISSUE TITLE
gecko plot API

### ISSUE THREAD

**Issue by elipapa** [opentargets/genetics#27]
An API, using clickhouse  as backend, which serves the data generated in https://github.com/opentargets/geckopipe. 

Data included in this release:
- [x] gtex,pchic,fantom5,dhs,vep for postgap parity
- [x] pQTL from Sun 2018

Queries:
- *at least parity*  chromosome/locus query as specified by https://github.com/opentargets/postgap-api/blob/master/src/schema.gql

Must discuss:
- [ ] graphql schema for new gecko plot with more filters

**Comment by mkarmona** [comment]
@peatroot @elipapa the linked schema.gql is the postgap one and it does not fit the new data structure.

**Comment by peatroot** [comment]
@mkarmona @elipapa, I'm currently getting all the data (grouped by S-IV-TV and TV-G), so can potentially just filter on the front-end. Can we therefore close this?

**Comment by peatroot** [comment]
Also discussed with @mkarmona.
