### ISSUE TITLE
Add variant to gene TSS distance to V2G table

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#271]
When calculating V2G scores, we would use the inverse of the distance.

Discussion from Slack:

> The above plots were only produced for lead variants that had at least 1 piece of evidence linking them to a gene in the V2G. In summary:
> - A total of 46,562 unique lead variants (p < 5e-8) were tested
> - 32,594 had at least 1 piece of evidence in the V2G, therefore 13,968 had none
> - Of the 32,594, the nearest coding gene was identified at _any_ rank in V2G for 19,431 lead variants, therefore it was not present for 13,163
> - Of the 19,431, the nearest coding gene was identified at rank 1 in V2G for 11,360 lead variants
> 
> > I’m puzzled about why there is no evidence associated with the nearest gene in so many cases - do these variants have any evidence connected to them at all?
> 
> 
> From the above figures, about half do not have any evidence at all, and the other half have evidence but not for the nearest gene. We currently only include evidence that passes multiple testing correction in our pipeline. I wonder whether we should include a low-weighted “gene distance” term when calculating the locus-to-gene scores that will be exported to the main platform. (edited)
> 
> 
> dunham [14 minutes ago]
> I think this might be reasonable. If we assigned the nearest gene that would give an assignment for the  13,968 that have nothing at least. The activity by contact model results support that this is a reasonable thing to do as in eh absence of hiC data they just use a power law distance parameter

**Comment by mkarmona** [comment]
@edm1 done. here the data will live `gs://genetics-portal-output/190129/distance` at the moment
