### ISSUE TITLE
Incorrect start-end positions of genes

### ISSUE THREAD

**Issue by emschmidt** [opentargets/genetics#277]
Positions listed as gene start and stop are incorrect on the Gene Page.

In some cases, the same position is listed as the start and stop. For example, https://genetics.opentargets.org/gene/ENSG00000101343

In other cases, the start position is greater than the stop position. For example, https://genetics.opentargets.org/gene/ENSG00000089101

Ideally, it would be good to have start and stop positions that match with Ensembl and UCSC (e.g. from the UTR).

**Comment by edm1** [comment]
There are two issues here:

1. In order for numbers to match Ensembl/UCSC, we will have to add UTR positions to the gene dictionary. Currently we are using the exons to define positions.

2. There is a bug, either with API or front-end that is causing (i) start == end, (ii) start > end, which should never be the case.

**Comment by peatroot** [comment]
The two cases above both happen at the API level.

**Comment by edm1** [comment]
```

**Comment by mkarmona** [comment]
[PR 50](https://github.com/opentargets/genetics-api/pull/50)
```
query sdfgsdfg {
  search(queryString:"ENSG00000101343") {
    genes {
      id
      symbol
      tss
      start
      end
    }
  }
}
```
```
{
  "data": {
    "search": {
      "genes": [
        {
          "id": "ENSG00000101343",
          "symbol": "CRNKL1",
          "tss": 20036690,
          "start": 20015012,
          "end": 20036690
        }
      ]
    }
  }
}
```
