### ISSUE TITLE
Dev Gene page is broken as the table does not render

### ISSUE THREAD

**Issue by mkarmona** [opentargets/genetics#288]
The table shown on the page `https://dev--genetics-app.netlify.com/gene/ENSG00000204084` does not render. The API call works as follow
```GraphQL
query asdf {
  studiesForGene(geneId:"ENSG00000204084") {
    study {
      studyId
      traitReported
      traitEfos
      pmid
      pubDate
      pubJournal
      pubTitle
      pubAuthor
      ancestryInitial
      ancestryReplication
      nInitial
      nReplication
      nCases
      traitCategory
      numAssocLoci
    }
  }
}
```
latest dev [API endpoint](http://open-targets-genetics.appspot.com/graphql/browser?query=query%20asdf%20{%0A%20%20studiesForGene(geneId%3A%22ENSG00000204084%22)%20{%0A%20%20%20%20study%20{%0A%20%20%20%20%20%20studyId%0A%20%20%20%20%20%20traitReported%0A%20%20%20%20%20%20traitEfos%0A%20%20%20%20%20%20pmid%0A%20%20%20%20%20%20pubDate%0A%20%20%20%20%20%20pubJournal%0A%20%20%20%20%20%20pubTitle%0A%20%20%20%20%20%20pubAuthor%0A%20%20%20%20%20%20ancestryInitial%0A%20%20%20%20%20%20ancestryReplication%0A%20%20%20%20%20%20nInitial%0A%20%20%20%20%20%20nReplication%0A%20%20%20%20%20%20nCases%0A%20%20%20%20%20%20traitCategory%0A%20%20%20%20%20%20numAssocLoci%0A%20%20%20%20}%0A%20%20}%0A}%0A&operationName=asdf)

**Comment by peatroot** [comment]
This is failing because the `search` query doesn't recognise `ENSG00000204084`, which happens before the `studiesForGene` query is called. @mkarmona, can you check why search isn't working for this gene?

**Comment by mkarmona** [comment]
oohh! thanks! I know search isn't working for dev env but I thought it would work partially. Don't worry about it I will be fixing the search soon.

**Comment by mkarmona** [comment]
@peatroot can we close this as resolved?

**Comment by peatroot** [comment]
Yes.
