### ISSUE TITLE
PheWAS plot

### ISSUE THREAD

**Issue by elipapa** [opentargets/genetics#29]
The PheWAS plot will be embedded within the variant page.

## Minimal API
Below is the subset of the graphql schema relevant to this plot. Until such time as the actual API gives full support, front-end will mock against this schema. Extra fields may need to be added, such as details of the publication or further statistics (odds ratio, standard error, etc.).
```
type Query {
    pheWAS(variantId: String!): PheWAS
}
type PheWAS {
    associations: [PheWASAssociation!]!
}
type PheWASAssociation {
    studyId: String!
    traitReported: String!
    traitCode: String!
    pval: Float!
    beta: Float!
    nTotal: Int # total sample size (variant level)
    nCases: Int # number of cases (variant level)
}
```

## Design
The key features that need to be supported are:
* chart
  * svg download
  * tooltip with row content
  * highlight on mouseover
* table
  * csv/tsv download
  * sorting by any column
  * infinite scroll or pagination
  * text search filtering by traitReported

Below are mock-ups of the plot and table.
<img width="1144" alt="screen shot 2018-07-31 at 14 26 08" src="https://user-images.githubusercontent.com/7376272/43462356-c543c9a4-94cd-11e8-830b-28c6298b30e3.png">
<img width="998" alt="screen shot 2018-07-31 at 14 26 22" src="https://user-images.githubusercontent.com/7376272/43462363-cd1b2fdc-94cd-11e8-96f0-d302ddb31f57.png">

**Comment by peatroot** [comment]
@opentargets/genetics, can you please take a look at https://admiring-dubinsky-cb7f95.netlify.com/variant/1_100314838_C_T (second table; beneath PheWAS) and comment on the following:
* Are the column names correct?
* What should the help text be in each column (there will be a pop-up tooltip)?
* Are we missing anything?

**Comment by edm1** [comment]
- Main title should show rsid in brackets after variant ID

**Associated genes**
- Title = 'Assigned genes'
- Subtitle = 'Which genes are functionally implicated by this variant?'

Existing columns:
- gene = 'Gene'
- g2v_score = 'Confidence' [High | Medium | Low | None]
- other columns to do later

**Associated studies**
Title = PheWAS
Subtitle = Which traits are associated with this variant in UK Biobank?

Existing column names:
- studyID = 'Study ID'
- traitReported = 'Trait'
- pval = 'P-value'
- nCases = 'N Cases' (blank if non case-control)
- nTotal = 'N Overall'
- Locus View

Additional columns:
- Beta (for everything)
- Odds ratio (only if case-control, exponent of Beta)

Other suggestions (if possible):
- Table to be sorted by pval ascending
- In plot, triangluar points showing direction of effect (+ve or -ve beta) (similar to pheweb).
- In plot, trait labels for significant points
- X-axis = 'Traits'

** Associated index variant **
Title = 'GWAS lead variants'
Subtitle = 'What GWAS lead variants are linked with this variant?'

Column names:
- indexVariant = 'Variant'
- indexVariantRsid = 'rsID'
- StudyId = 'Study ID'
- traitReported = 'Trait'
- pval = 'P-value'
- pmid = 'PMID'
- combined pub = Author et al (year)
- no journal information
- nTotal = 'Study N'
- no case numbers
- overallR2 = 'LD (R-squared)'
  - tooltip = 'Linkage disequilibrium with the queried variant'
- don't show log10ABF or posteriorProbaility
- Column titled 'Is in 95% Credible Set' [True|False|No information]

** Associated tag variants **
Title = 'Tag variants'
Subtitle = 'Which variants tag (through LD or finemapping) this lead variant?'

Column names:
- indexVariant = 'Variant'
- indexVariantRsid = 'rsID'
- StudyId = 'Study ID'
- traitReported = 'Trait'
- pval = 'P-value'
- pmid = 'PMID'
- combined pub = Author et al (year)
- no journal information
- nTotal = 'Study N'
- no case numbers
- overallR2 = 'LD (R-squared)'
  - tooltip = 'Linkage disequilibrium with the queried variant'
- Column titled 'Is in 95% Credible Set' [True|False|No information]
- posteriorProbaility = 'Posterior probability'
  - tooltip = 'Posterior probability from finemapping that this tag variant is causal'
- don't show log10ABF

Other ---------

It would be nice (but not absolutely necessary) to have additional information (from the Ensembl API?) about the variant at the top of the page. Depending on what is available from Ensembl:
- Minor allele frequency (in different populations)
- Most severe consequence across any gene (this is available from Ensembl). We only have per gene consequences.

Notes, Ed to discuss with Miguel:
- For column 'Is in 95% Credible Set', we need to add an additional column showing whether finemapping was conducted (study ID will appear in finemapping table)
- log odds to be converted to ORs for case-control

Notes for FAQ:
- PheWAS uses UK Biobank (v1) only. GWAS CAtalog will be included later.
- Beta is log odds ratio for case-control studies.
- What does it mean to for variants to be linked? LD or credible set.
