### ISSUE TITLE
Update FAQ and documentation

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#308]
Main things to include:

- [x] How effect size harmonisation is done
- [x] Why some effect sizes are missing
- [x] Why some studies have a mix of betas and OR
- [x] How GWAS Catalog studies have been split into separate study IDs
- [x] Some GWAS Catalog studies are clustered
- [x] V2G includes distance
- [ ] Colocalisation methods
- [ ] How scoring doesn't integrate the colocalisation scores

**Comment by MayaGhoussaini** [comment]
Regarding V2G , we also need to add that VEP consequences for UTR and intronic variants are no longer weighted zero
