### ISSUE TITLE
Colocalization query

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/genetics#310]
Hello Genetics Team,

Given that I can retrieve a set of associated gene-SNP-traits, I would like to check whether there is a colocalization signal for that SNP or tagged SNPS. 
Basically, I would like to know if the eQTL or pQTL is relevant for the trait and gene  for further investigation (i.e. functional study).

**Comment by MayaGhoussaini** [comment]
Hi Gautier,

This is not ready yet.
Should be ready by end of May. Ed will be running the coloc across all GWAS summary stat, new eQTL database and GTEX in the next few weeks.
Best,
Maya


--
Maya Ghoussaini, PhD
Genetic Analysis Team Leader
Open Targets, Wellcome Trust Sanger Institute
Hinxton, Cambridge CB10 1SD, UK
Tel: +44 (0) 1223494378
Email: mg29@sanger.ac.uk<mailto:hf6@sanger.ac.uk>

**Comment by ElaineMcA** [comment]
Adding to release 3.0.

**Comment by edm1** [comment]
GraphQL colocalisation queries are specified here and will be implemented for the next release: https://github.com/opentargets/genetics/issues/339
