### ISSUE TITLE
Streamline release process

### ISSUE THREAD

**Issue by mkarmona** [opentargets/genetics#312]
A table showing on which domain have to be served the webapp and which api endpoint has to be pointing to

- [x] genetics.opentargets.org -> genetics-api.opentargets.io
- [ ] genetics-qa.opentargets.org -> genetics-api-qa.opentargets.io
- [ ] genetics-dev.opentargets.org -> open-targets-genetics.appspot.com

Elaborating a bit more each point

1. genetics.opentargets.org keeps the current production across 3 geo-locations
2. genetics-qa.opentargets.org keeps the next already frozen next data release coming with api and frontend deployed on same infrastructure as production but limited to EU. this will help to evaluate the new features and allows to fix potential bugs or issues
3. genetics-dev.opentargets.org keeps latest changes on development process and it can be broken at any time

**Comment by peatroot** [comment]
There are now netlify deploys for each of your API versions above at:
• `dev`: https://dev--genetics-app.netlify.com
• `qa`: https://qa--genetics-app.netlify.com
• `production`: https://genetics-app.netlify.com

The DNS in Google Cloud still needs to be set up though, @mkarmona.
• https://genetics-dev.opentargets.org/ --> https://dev--genetics-app.netlify.com
• https://genetics-qa.opentargets.org/ --> https://qa--genetics-app.netlify.com
• https://genetics.opentargets.org/ --> https://genetics-app.netlify.com
