### ISSUE TITLE
Curate a list of checks for systematic QC review before production release

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/genetics#313]
Curate a set of genes-variants-traits that may routinely be used to complete QC review in a systematic manner in advance of future releases.

Some checks could then be automated in the future.

@emschmidt @MayaGhoussaini - need your help to compile as you are less involved in data pipeline itself and can wear a "user" hat.

**Comment by deniseOme** [comment]
Happy to put a user hat here too. Would that be ok @ElaineMcA?

@emschmidt @MayaGhoussaini this is what we look for in the Platform before any given release (FYI):
https://docs.google.com/spreadsheets/d/1x0fNHWihX_OHdFu7QpFOGQHqpDhFG__nQxn5LgUXE0A/edit#gid=1590908404

How about if we start off populating this sheet, currently in "Genetics Portal v3.0 Mar 2019"
https://drive.google.com/drive/folders/1tYY-Ohq6-pEUzvxV164UmMloXPMQjjQl

In addition to genes-variants-traits, we can double check with other web functionalites are working fine e.g. download table or image, clicking on links, tooltips, etc..

**Comment by d0choa** [comment]
This spreadsheet wasn't used for the previous release of genetics portal (Feb 2020).
We should allocate time and perform a proper manual QC in the next portal release.

Would you @deniseOme consider there is more work to do on completing the spreadsheet?

**Comment by deniseOme** [comment]
@d0choa, the work is now complete and include data to be checked re. L2G pipeline, gene prioritisation visualisations, etc.

https://docs.google.com/spreadsheets/d/1_s-Qy3I_Ki2MOhG6n0e5bquBqviaLob9kDyQLrDqRYw/edit?usp=sharing

As new data and visualisations get introduced, we should update the sheet accordingly.
