### ISSUE TITLE
Changes to the main pipeline

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#334]
LUTs:
- [x] Use GRCh38 gene dict: `gs://genetics-portal-data/lut/homo_sapiens_core_96_38_genes.json`
- [x] Make sure that the tissue LUT is up-to-date
- [x] New display labels for variant page: `gs://genetics-portal-data/lut/v2g_display_labels.190524.json`

Variant index:
- [x] Use the fields `chrom_b38` and `pos_b38` instead. If possible can we keep the `chrom_b37` and `pos_b37` in the database, it would be good to show in the variant summary on the variant page.

V2G:
- [ ] ~The QTL data is now in parquet format as it is taken directly from our summary stat bucket. The way this data is loaded will need to be changed. Also, the parquet dataset includes many additional eQTL datasets. If we decide not if include these in version 3, they will need filtering out, e.g. `filter(col('study_id') == 'GTEX_v7' | col('study_id') == 'SUN2018')`.~
- [ ] ~It is also possible the names "GTEX_v7" and "SUN2018" are not consistent with the current pipeline. For example, in the V2G scoring.~
- [x] Interval data here `gs://genetics-portal-data/v2g/190521/interval`
- [x] QTL data here `gs://genetics-portal-data/v2g/190521/qtl`
- [x] QTL data has been "hacked" to combine source and feature into one composite field. All the required fields are inside the parquet (they don't need parsing from `input_file_name()`). Let me know if I have got any field names incorrect.
- [x] The bio_feature display label LUT has been updated `gs://genetics-portal-data/lut/biofeature_lut_190328.w_composites.json`
- [x] V2G scoring weights have been updated and converted to json: `gs://genetics-portal-data/lut/v2g_scoring_source_weights.190521.json`

V2D:
- [x] The study table now has a `has_sumstats` field, it would be useful to return this in the API.
- [x] Updated files here `gs://genetics-portal-data/v2d/190521`. ~Still waiting on LD and overlap tables.~

PheWAS:
- [x] Should come from the new table
- [x] I think the case fields are simpler in the new sumstat data.

**Comment by mkarmona** [comment]
@edm1 there is another file I use that is called [v2g_display_labels](https://github.com/opentargets/genetics-api/blob/master/resources/v2g_display_labels.json) which we should check whether it needs updates or not
