### ISSUE TITLE
Make Open Targets Platform links customisable inside the Genetics portal

### ISSUE THREAD

**Issue by forus** [opentargets/genetics#338]
Open Targets Platform links inside the Genetics portal are hard-wired to www.targetvalidation.org. 

We need to have a way to specify a different hostname for the links.
It would be nice to specify that while building the frontend application as it's already done for the api (see `REACT_APP_GRAPHQL_API_URL`).

**Comment by forus** [comment]
@peatroot Hi, Gareth! I am wondering whether it's something you would be able to pick up.

**Comment by peatroot** [comment]
Hi @forus, good idea. I've tried to generalise the environment variable handling a bit in https://github.com/opentargets/genetics-app/pull/119. Feel free to suggest other things that'd be helpful to move into environment variable configuration.
