### ISSUE TITLE
replicate the analysis of the paper doing MR analysis between gwas and eQTL

### ISSUE THREAD

**Issue by elipapa** [opentargets/genetics#34]
https://www.biorxiv.org/content/early/2018/07/25/377267

>summary statistics-based Mendelian Randomization approach that uses multiple SNPs jointly as instruments and multiple gene expression traits as exposures, simultaneously

**Comment by edm1** [comment]
We will look into this once the coloc is in place. In the mean time we may include MR-EvE data.
