### ISSUE TITLE
Descontinue jsonlines in favour of parquet

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#345]
Clickhouse [now accepts Parquet](https://clickhouse.yandex/docs/en/interfaces/formats/#data-format-parquet) as input format. We need to update all input data to use parquet instead of jsonlines.

Repositories this affects:
- [x] Sumstats (filtered)
- [ ] Credible set output
- [x] Coloc output

**Comment by mkarmona** [comment]
@edm1 it is worth noting clickhouse support a limited version of parquet format as lists and maps are not currently supported. Although it is ok having those 3 datasets generated as they don't contain any composed field

**Comment by edm1** [comment]
The credible set output from the fine-mapping pipeline is required to be in json format for my current colocalisation pipeline. Therefore, I don't plan to change this to parquet yet.
