### ISSUE TITLE
Update EFO annotations for UK Biobank studies

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#353]
These are required for #344 #346 #348.

This is currently blocked. by Zooma

**Comment by deniseOme** [comment]
Zoë (EFO) has kindly done the mapping for another project of ours with MalaCards.

This should be all ICD10 refs in EFO:
https://docs.google.com/spreadsheets/d/1GSOkYegyQOdz21gdhMEex6gkOsHzlF9DWApq096FIo8/edit?usp=sharing

Note there may be multiple for each term which she has kept in separate fields.

@MichaelaEBI and I are currently looking into this file.

**Comment by hammer** [comment]
@deniseOme whoa this spreadsheet is very useful! Do you have any information on how it was created?
