### ISSUE TITLE
GCST003044 has been removed from GWAS Catalog

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#354]
...due to a curation error, so is not found in our study table. However, I have summary statistics for it so it exists in our credible set and colocalisation table.

@mkarmona Will this break the API?

**Comment by mkarmona** [comment]
@edm1 having the study in the study table is a prerequisite for the api when a study object is required

**Comment by edm1** [comment]
List of all studies that have summary statistics but are not showing up in the study table:

```
GCST006363
GCST005068
GCST006348
GCST006358
GCST005072
GCST005063
GCST006352
GCST005070
GCST003497
NEALE2_6160_1
GCST006357
GCST005061
GCST006345
GCST006359
GCST005058
GCST006347
GCST006355
GCST005073
NEALE2_670_1
GCST006344
GCST006354
GCST005074
GCST005062
GCST006349
GCST005059
GCST005069
GCST005060
GCST005067
GCST006327
NEALE2_6142_7
GCST005065
GCST003044
GCST006362
GCST006350
GCST006938
GCST006346
GCST005071
GCST005066
GCST006351
GCST005353
GCST005064
GCST006328
```

**Comment by edm1** [comment]
Fixed by https://github.com/opentargets/genetics-v2d-data/commit/99fb8fdadaff0bf87c956837b179c482d790f9d6
