### ISSUE TITLE
being able to change `7_24966446_C_A` to `rs123` on the URL

### ISSUE THREAD

**Issue by deniseOme** [opentargets/genetics#356]
_Note: User's request sent to Genetics support (Assistant Professor at University of Maryland School of Medicine)_

They would like to be able to "to send an rsNumber directly, perhaps something like: https://genetics.opentargets.org/rsid/rs12403995".

I agree this could make navigation and use of Open Targets Genetics more streamlined and friendly.

If I'm on a page like this 
https://genetics.opentargets.org/variant/7_24966446_C_A

I could then change it to another SNP such as rs666 just by swapping the coordinates by the rsID (that is easier to remember) in the location bar. This would avoid the need to search for a new SNP. E.g.

https://genetics.opentargets.org/variant/7_24966446_C_A
https://genetics.opentargets.org/variant/rs123

would both lead to the same page.

Ensembl does allow for similar tweak: when on a gene page like this for OSBPL3:
http://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000070882;r=7:24796540-24981634

if I want to get to the same page for another gene such as DMD I can simply change the `g=ENSG00000070882` to `g=DMD` and voila!

(the coordinates on the URL in Ensembl don't change in the location bar, but the page does show the right location - chr X - for my new gene i.e. DMD

If this we decide not to allow this for Open Targets Genetics, please let me know so that I can get back to the user.

**Comment by edm1** [comment]
This will not be possible as rsIDs are not unique to a single variant.

The only way this could work, is if the url takes you to a search results page on which you then select a unique variant.

**Comment by deniseOme** [comment]
That's a pity. But thanks for the prompt reply. 

@edm1 @mirandaio @peatroot I will close this but feel free to reopen it if we change the way that we display a search results page.
