### ISSUE TITLE
Front-end changes: Home page / search results

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#357]
- [x] Make users aware that all positions are build GRCh38. Something like: "Note: All genomic coordinates are now based on GRCh38"

Search results
- [x] An icon showing whether the study `has_sumstats`. 

Default buttons:
- [x] LDL cholesterol Klarin (GCST006612) to be changed to Willer (GCST002222)
- [x] GCST003044_1 changed to GCST003044
- [x] Variant buttons to point to 1_154453788_C_T

**Comment by peatroot** [comment]
Closing as done
