### ISSUE TITLE
Front-end changes: Variant page

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#359]
Variant summary:
- [x] Show GRCh37 chrom, position information

Assigned genes section:
- [x] eQTL and pQTL labels are missing, I’ve updated these in `gs://genetics-portal-data/lut/v2g_display_labels.190524.json` and I assumed these were passed through the API

PheWAS section:
- [x] Needs updating so it works with the new API
- [x] Subtitle: “Which traits are associated with this variant in the UK Biobank and GWAS Catalog summary statistics repository? Only traits with P-value < 0.05 are returned.”
- [x] The significance line need to be changed because we are pre-filtering the summary statistics. It is no longer correct to use 0.05 / (number of traits returned). We need to use 0.05 / (total number of traits tested). We should approximate “total number of traits tested” as the total number of traits in our summary stat table. It would be best for this to be returned by the API. @mkarmona 
- [x] Locus plot link to pre-select study as well as variant

GWAS lead variants section:
- [x] ~Only show “Colocalisation” button if there are summary stats available for that study~(`has_sumstats` in the study table). @andrewhercules suggests always showing the button but only active where `has_sumstats` is True.
  - Tooltip when active: "View colocalisation results at this locus"
  - Tooltip when inactive: "Colocalisation results are only available for studies that have summary statistics available"

**Comment by mkarmona** [comment]
@edm1 the display labels [were updated](https://github.com/opentargets/genetics-api/blob/mk-minorrefactor/resources/v2g_display_labels.json). Don't use that file anymore as it is also missing tss row by example; any new addition open an issue and assign it to me please.
@peatroot [here you can find](https://open-targets-genetics.appspot.com/graphql/browser?query=query%20sdfgsdfg%20%7B%0A%20%20genesForVariantSchema%20%7B%0A%20%20%20%20qtls%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20sourceId%0A%20%20%20%20%20%20sourceLabel%0A%20%20%20%20%20%20sourceDescriptionOverview%0A%20%20%20%20%20%20sourceDescriptionBreakdown%0A%20%20%20%20%20%20pmid%0A%20%20%20%20%20%20tissues%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20intervals%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20sourceId%0A%20%20%20%20%20%20sourceLabel%0A%20%20%20%20%20%20sourceDescriptionOverview%0A%20%20%20%20%20%20sourceDescriptionBreakdown%0A%20%20%20%20%20%20pmid%0A%20%20%20%20%20%20tissues%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20functionalPredictions%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20sourceId%0A%20%20%20%20%20%20sourceLabel%0A%20%20%20%20%20%20sourceDescriptionOverview%0A%20%20%20%20%20%20sourceDescriptionBreakdown%0A%20%20%20%20%20%20pmid%0A%20%20%20%20%20%20tissues%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20distances%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20sourceId%0A%20%20%20%20%20%20sourceLabel%0A%20%20%20%20%20%20sourceDescriptionOverview%0A%20%20%20%20%20%20sourceDescriptionBreakdown%0A%20%20%20%20%20%20pmid%0A%20%20%20%20%20%20tissues%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) the query to get all display labels and it seems to be working.

**Comment by mkarmona** [comment]
@peatroot for the phewas plot I will return a field called `totalGWASStudies` where there is that number the total unique studies for the whole gwas sumstats dataset

**Comment by peatroot** [comment]
Closing as done
