### ISSUE TITLE
Front-end changes: Locus page

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#361]
- [x] ~Only show “Colocalisation” button if there are summary stats available for that study (`has_sumstats` in the study table).~ @andrewhercules suggests always showing the button but only active where `has_sumstats` is True.
  - Tooltip when active: "View colocalisation results at this locus"
  - Tooltip when inactive: "Colocalisation results are only available for studies that have summary statistics available"

**Comment by peatroot** [comment]
Closing as done
