### ISSUE TITLE
Front-end changes: Study-locus page

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#362]
- [x] rsID for the page’s lead variant
- [x] Link to variant page
- [x] Link to locus page (with study, variant) selected
- [x] We need a way to tell what the beta is for the lead variant of the page that we’re on. I don’t think there is currently an API call that will give this information specifically? It is available from the credible set information, or could be provided with a new API call to the sumstat table.

Both QTL and GWAS coloc tables:
- [x] (table) H3 tooltip: “Posterior probability that the signals **do not** colocalise”
- [x] (table) H4 tooltip: “Posterior probability that the signals colocalise”
- [x] (table) log2(H4/H3) tooltip: “Log-likelihood that the signals colocalise”
- [x] show right variant

QTL coloc section:
- [x] (heatmap) Add “Source” for consistency
- [x] (heatmap and table) “Phenotype” to be called “Molecular Trait”
- [x] (table) QTL beta tooltip: “QTL effect with respect to the alternative allele of the page variant”

GWAS colocalisation section:
- [x] No heatmap (for now)
- [x] Do we want a link to jump to the Study-locus page for each (study, variant) pair?
- [x] (table) Beta tooltip: “Effect with respect to the alternative allele of the page variant”

Credible Set Overlap visualisation:
- [x] 95% toggle doesn’t seem to do anything
- [x] Set default H4 to 0.95
- [x] Change “all” to “PP > 0.1%”

**Comment by peatroot** [comment]
Closing as done
