### ISSUE TITLE
hyperlinking words/sentences on Genetics homepage

### ISSUE THREAD

**Issue by deniseOme** [opentargets/genetics#366]
Some sentences on the Genetics HP are in blue and look like links. But they are not hyperlinked.

The original idea according to @andrewhercules was that this text could be linked to the docs  hyperlinked to pages on the docs. Ideally wherever word/sentence we link out to should take to a page with an identical title e.g. `fine mapping analyses` on the HP should point to a page on the docs entitled `fine mapping analyses`. We have `fine mapping expansion` instead:

https://genetics-docs.opentargets.org/our-approach/assigning-traits-to-loci#fine-mapping-expansion

So either we rename the sentence on the HP or the title on the docs. Alternatively we don't care if we link to a page with a different name from the hyperlinked word.

These are the sentences and URLs to link to:

* Variant-to-Gene (V2G) scoring: https://genetics-docs.opentargets.org/our-approach/data-pipeline#scoring 

note: ideally we should have identical names for the link out sentence and the title of the page we land 

* multi-trait comparison: https://genetics-docs.opentargets.org/how-to-use-open-targets-genetics-starting-with/multiple-traits-or-diseases

Again no resemblance on the names. 

* variant-gene-trait: https://genetics-docs.opentargets.org/our-approach/pipeline-overview

I'd recommend not highlighting the words `variant-gene-trait` as we don't do that for Open Targets Platform or corporate site

**Comment by andrewhercules** [comment]
Agreed - we should link each word to the relevant section in the documentation. Although the text on the homepage and the title of the documentation page do not need to be an exact match, as long as the user is provided with an overview or description of the term/topic/idea/word that is highlighted as a link.

The link ideas above are great and I don't think we need to change either the text or the documentation page. That being said, if we want to describe the main Portal features differently or highlight other key features, we can also make those changes - but I leave that up to the Core Genetics team.

And I also agree - we can remove the blue from the ``variant-gene-trait`` term in the main search box.

@peatroot and/or @mirandaio, can you please make the links identified by @deniseOme above?

**Comment by deniseOme** [comment]
@andrewhercules, there may be different schools of thoughts for exact match versus non-exact match. I have been recommended to follow the former, which is what I have been trying to do for Open Targets Platform.

I will follow this up with @MayaGhoussaini @emschmidt @edm1.

**Comment by deniseOme** [comment]
Discussed this with @emschmidt who pointed out we need to include the colocatisation analysis as well on the homepage for the upcoming release.

Not sure we will create another image, @andrewhercules ?

**Comment by andrewhercules** [comment]
We can update the image - add a hexagon and label - if there is an icon that represents the main idea of colocalisation. 

So for example:

- [location pin](https://thenounproject.com/search/?q=location&i=2017554)
- [multiple map pins](https://thenounproject.com/search/?q=multiple%20locations&i=1062197)
- [map locations](https://thenounproject.com/term/map-locations/496735/)
- [map points](https://thenounproject.com/term/map-location/1752338/)
- [map pin with check mark](https://thenounproject.com/term/pin/1670770/)

Feel free to check out [The Noun Project](https://thenounproject.com/) and let me know if any other icons are suitable - I have a full membership so we can use any icon we want.

**Comment by andrewhercules** [comment]
Issue closed as homepage text has been updated to coincide with version 5 release
