### ISSUE TITLE
HMGCR not showing up as Top V2G gene for (GCST002222, 5_75329662_C_A)

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#371]
Also seems to be an issue with the Top V2G aggregation:

https://dev--genetics-app.netlify.com/study/GCST002222
<img width="1292" alt="Screen Shot 2019-06-11 at 10 51 34" src="https://user-images.githubusercontent.com/1938268/59262376-fbac3380-8c36-11e9-8143-ba7223a21554.png">

https://dev--genetics-app.netlify.com/variant/5_75329662_C_A
<img width="1286" alt="Screen Shot 2019-06-11 at 10 51 44" src="https://user-images.githubusercontent.com/1938268/59262385-0070e780-8c37-11e9-925d-3e5b9598b8f4.png">

**Comment by mkarmona** [comment]
@edm1 fixed. I changed the type of variant we use for the aggregation. Now, we are getting the tag variant from the intersection table which gives you what the column description stands for
