### ISSUE TITLE
VEP consequences terms seem clickable on the variant page

### ISSUE THREAD

**Issue by deniseOme** [opentargets/genetics#372]
@mirandaio @peatroot, consequence terms returned by the VEP on the variant page are in blue and seem to be clickable.

e.g. https://dev--genetics-app.netlify.com/variant/6_31576865_A_G
(intron_variant)

Can have that in grey or other colour so that the user does not feel like clicking on that name please?

**Comment by andrewhercules** [comment]
Ticket closed as VEP consequence terms shown in default font colour `#5a5f5f`

![Screenshot 2021-06-07 at 20 21 19](https://user-images.githubusercontent.com/7490258/121076121-f1918100-c7cd-11eb-896e-14e9f883e2da.png)
