### ISSUE TITLE
batch calculate the closest gene for all variants in our index

### ISSUE THREAD

**Issue by elipapa** [opentargets/genetics#38]
We need to display the closest gene if no rows are returned by the select statement on the v2g table. 

For each variant, we should calculate the closest _protein coding_ gene *and* the closest _non coding_ gene (defined as the closest 5') and save them in the variant index.

The API should return closest coding and non-coding genes, whenever a variant query is performed.

**Comment by ElaineMcA** [comment]
Not priority/ should not block achievement of early beta review by end Aug.

**Comment by edm1** [comment]
Workflow for getting closest gene (protein-coding and "any") has been added here: 
https://github.com/opentargets/v2g_data

Currently running on Sanger farm.

**Comment by edm1** [comment]
Closest gene assignment is in staging `gs://genetics-portal-staging/v2g/closest_gene/180830/closest_gene.tsv.gz`. Columns outlined [here](https://github.com/opentargets/v2g_data/#other-datasets).

For protein coding gene assignment, only protein coding _transcripts_ are used. Ian has suggested I also check that my output matches VEP's `--nearest gene` output. I will do this before copying to `gs://genetics-portal-data/v2g/closest_gene/`.

**Comment by edm1** [comment]
I have run `vep --nearest gene` for 10,000 variants and the output matches my results exactly.
https://github.com/opentargets/v2g_data/tree/master/tests/check_nearest_gene

I have copied the file from staging to `gs://genetics-portal-data/v2g/nearest_gene.tsv.gz`.

Note: This file contains the nearest (i) protein coding gene (ii) nearest _any_ gene. I would vote for using the nearest protein coding gene in the Genetics Portal (at least to begin with).
