### ISSUE TITLE
Multiple identifiers for the same study 

### ISSUE THREAD

**Issue by BjornWouters** [opentargets/genetics#380]
I came across a study which was divided into three identifiers (separated with an underscore) describing the same study with different variants and study names. 

The identifiers are: 
[GCST005863_1](https://genetics.opentargets.org/study/GCST005863_1)
[GCST005863_2](https://genetics.opentargets.org/study/GCST005863_2)
[GCST005863_3](https://genetics.opentargets.org/study/GCST005863_3)

The GWAS catalog has all the variants in the same study. 

Is this done on purpose and if so, what is the reason behind it? Because I couldn't find any explanation behind this feature. 

Thanks,

Bjorn Wouters

**Comment by BjornWouters** [comment]
Found out that the studies are created per p-value annotation in GWAS catalog. 
Is this a suitable way to define a study in Open Targets? Many studies use their P-value annotations for different reasons. As an [example](https://www.ebi.ac.uk/gwas/studies/GCST006585), this study uses the annotation to define their mapped gene resulting in a study per variant in Open Targets.

**Comment by edm1** [comment]
@BjornWouters you are correct in thinking that they are split by p-value text field.

In the past, GWAS Catalog would sometimes curate multiple GWAS analyses (e.g. different ancestries, sexes) from the same publication under the same study accession. The only way to differentiate these is by the `P-VALUE (TEXT)` field.

I've therefore split these compound phenotypes into the separate study IDs that you're seeing. I see that `GCST005863_2` and `GCST005863_3` are for "Japanese" and "japanese", respectively, which they shouldn't be. This error comes from the GWAS Catalog curation.

In the future, GWAS Catalog will no longer curate separate studies under the same accession, so this problem will fix itself.

**Comment by BjornWouters** [comment]
@edm1, thanks for the fast reply and good to hear that the problem will fix itself.
