### ISSUE TITLE
State which allele is the "Effect allele" explicitly in the Variant Summary

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#385]
It was requested by a user at ESHG that we explicitly say which is the effect allele at the top of the variant page. Under "Location" in the "Variant Summary" section of the variant page, add:

```
Reference allele: <ref>
Alternative allele (effect allele): <alt>
```

E.g. on this page: https://genetics.opentargets.org/variant/1_154453788_C_T. That section would look like:
```
GRCh38: 1:154,453,788
GRCh37: 1:154,426,264
Reference allele: C
Alternative allele (effect allele): T
```

Additionally, can we change the subtitle of the gnomad frequencies from "Population allele frequencies" to "Effect allele population frequencies".

**Comment by deniseOme** [comment]
This has also been requested by Sanofi user via email back in May 2019.

"Hi I was exposed to the open target genetics in the EBI industry workshop. The web site is helpful. I was wondering which allele was used Neal lab’s PheWAS analysis? It is not reported. It would be nice to show the effector allele and effector allele freq (to help resolve G/C A/T variants)".

Reply sent, [FAQ](https://genetics-docs.opentargets.org/faqs#what-is-the-effector-allele) created.

**Comment by deniseOme** [comment]
@edm1 @emschmidt @MayaGhoussaini have suggested to add a column to the variant page, located between "Variant summary" and "Location" i.e.

<img width="317" alt="Screen Shot 2019-08-12 at 17 18 12" src="https://user-images.githubusercontent.com/6472381/62880427-43c60000-bd25-11e9-852d-b678b884d65e.png">

This new column would contain the following (or a variation of it):
chr_coordinate_reference_alternative(effect)allele
