### ISSUE TITLE
Update data download page on docs

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#387]
Isn't pointing to the latest

https://genetics-docs.opentargets.org/technical-pipeline/data-download

Do we have a checklist of todos for each release?

**Comment by deniseOme** [comment]
good point @edm1. AFAIK we don't have a checklist of TODOs for each release, only a tentative version for manual QC.

I'm happy to start collating some of these TODOs and share with the team for further input/additions.

As per the downloads page, @mkarmona suggested to wait till the mini release is out to update the docs.

Following chats with @ElaineMcA, when/if the version changes are captured in a centralised place (GitHub, Google drive), she is happy to update the docs, as she does already for the Platform:
https://docs.targetvalidation.org/technical-pipeline/change-log

**Comment by ElaineMcA** [comment]
Change log now in place here:  https://genetics-docs.opentargets.org/technical-pipeline/change-log

@deniseOme to initiate draft to dos for review at team meeting.

**Comment by andrewhercules** [comment]
Ticket closed as change log available in documentation along with data download links
