### ISSUE TITLE
Question regarding the locus overlap parquet file

### ISSUE THREAD

**Issue by BjornWouters** [opentargets/genetics#388]
Hi there,

While processing a single GWAS study and creating all the corresponding parquet files I ended up with some questions regarding the study overlap table. 

My first question is why both variant overlap between studies and overlap of other variants within a certain range are stored. This will result in the storage of redundant information with variants laying close to each other. Is there a particular reason why the overlap of variants within the 5Mb range is stored?

Secondly, looking at the snapshot of the loaded database, I came across overlap between two studies with the same study identifier. Is this done on purpose? 

My last question is that some variants between study A and study B laying nearly next to each other have totally different overlap values. This is also based on the studies_overlap table of the snapshot of the database. How could the overlap of variants between the same studies on nearly identical loci differ in such a way that there is different overlap? 

GCST001264_1 is an example of a study identifier which shows these phenomena. 

All the other parquet files are working perfectly, I was just wondering if I maybe missed some essential information regarding the locus overlap table.

**Comment by edm1** [comment]
@BjornWouters The overlap table gives the number of overlapping tag variants for all independent disease-associated loci with <5Mb of each other across the genome. A disease-associated loci is identifiable by a study_id and lead variant (chrom, pos, ref, alt).

> Secondly, looking at the snapshot of the loaded database, I came across overlap between two studies with the same study identifier. Is this done on purpose?

The overlap table is a symmetrical matrix stored in long format. It contains values along the diagonal, i.e. (study, lead variant)s against themselves

> some variants between study A and study B laying nearly next to each other have totally different overlap values...How could the overlap of variants between the same studies on nearly identical loci differ in such a way that there is different overlap?

If we're comparing, e.g.

(study A, lead X) against (study B, lead Z)
and
(study A, lead Y) against (study B, lead Z)

Then (study A, lead X) and (study A, lead Y) are, by definition, independent of each other. They should lie on separate haplotypes, and so there should be no/very few tag variants in common between them. Therefore the comparison of each against (study B, lead Z) should give very different results.

**Comment by BjornWouters** [comment]
@edm1 Thanks for the fast reply and clarification of the locus overlap table! Will close this ticket as everything is clear now.
