### ISSUE TITLE
distance dataset takes too long to compute

### ISSUE THREAD

**Issue by mkarmona** [opentargets/genetics#390]
Something changed from previous versions and it slowing down the generation process at least more than the double the time it usually took with previous versions.

**Comment by hammer** [comment]
@mkarmona how was this issue resolved?

**Comment by mkarmona** [comment]
@hammer , the the default url for a spark cluster is empty which means it will get the env cluster configuration by default. in the case you want to run it locally you might want to pass [another conf with that var overwritten](https://github.com/opentargets/genetics-pipe/pull/26#issuecomment-512578609).
