### ISSUE TITLE
Add link to UK Biobank showcase to distinguish phenotypes

### ISSUE THREAD

**Issue by emschmidt** [opentargets/genetics#394]
Sometimes it is impossible to distinguish between two UK Biobank studies based on the given study information in the portal. For example, when you search for 'Body mass index', there are two identical-looking Neale results (but with different N and associated loci). One has UK Biobank showcase definition 21001 and one has definition 23104.

![Screen Shot 2019-07-31 at 9 32 36 AM](https://user-images.githubusercontent.com/9885342/62196800-93481b80-b376-11e9-90a6-eae7864ac11f.png)

For the Neale2 studies, please add an external reference link on the study page to the UK Biobank showcase. For example, http://biobank.ndph.ox.ac.uk/showcase/field.cgi?id=21001
The 'id' can be found by striping 'NEALE2_' and '_raw' from study page URL.

**Comment by andrewhercules** [comment]
As discussed in Slack, we can also support links to FinnGen using a similar approach of taking the endpoint ID. (e.g. https://r5.finngen.fi/pheno/AD_LO)

Can we please adjust the logic in [lines 18-64 of the StudySummary.js file](https://github.com/opentargets/genetics-app/blob/bd664ca9a5747e2defed987441089402183fe769/src/components/StudySummary.js#L19) to do the following?

### FinnGenn

![Screenshot 2021-06-08 at 12 22 57](https://user-images.githubusercontent.com/7490258/121176651-5d1e3180-c854-11eb-8bd5-5cc6e096942c.png)

- [ ] Display **FinnGen:** when `studyId.startsWith('FINNGEN')
- [ ] Generate a link by taking the `studyId`, remove the "FINNGEN_R5_" part of the string to obtain just the FinnGen endpoint ID (e.g. AD_LO), and link to `https://r5.finngen.fi/pheno/`+  `FinnGenn endpoint ID` (e.g. https://r5.finngen.fi/pheno/AD_LO); also use the `FinnGenn endpoint ID` as the link label  

### UK Biobank
- [ ] Remove the existing link to the Neale UK Biobank homepage - see [line 23](https://github.com/opentargets/genetics-app/blob/bd664ca9a5747e2defed987441089402183fe769/src/components/StudySummary.js#L23)
- [ ] Generate a link by taking the `studyId`, remove the "NEALE2_" and "_raw" or "_xxxxx" part of the string to obtain just the UK Biobank endpoint ID (e.g. 21001), and link to `http://biobank.ndph.ox.ac.uk/showcase/field.cgi?id=`+  `UK Biobank endpoint ID` (e.g. http://biobank.ndph.ox.ac.uk/showcase/field.cgi?id=21001); also use the `UK Biobank endpoint ID` as the link label

**Comment by ktsirigos** [comment]
closing this one as work is done.
