### ISSUE TITLE
Make use of milestones?

### ISSUE THREAD

**Issue by hammer** [opentargets/genetics#398]
I have found the platform team's recent adoption of [milestones](https://github.com/opentargets/platform/milestones) to be quite useful when trying to coordinate our internal development plans with the upstream Open Targets development plans. It appears the genetics team used milestones in the past; is there any possibility that milestones might be used again in the future to assign issues to releases that others can use to plan around?

**Comment by ElaineMcA** [comment]
Absolutely,  over the coming weeks and months, we have a plan to bring on additional resource and as part of that, next milestones can be defined and included on this repo also.

**Comment by andrewhercules** [comment]
Ticket closed as Open Targets plans and roadmaps will be made available through the [Open Targets Community](http://community.opentargets.org/).
