### ISSUE TITLE
Origin of LD reference for fine mapping?

### ISSUE THREAD

**Issue by hammer** [opentargets/genetics#406]
https://github.com/opentargets/genetics-finemapping/blob/master/2_make_manifest.py#L33 references the files `/home/ubuntu/data/genotypes/ukb_v3_downsampled10k_plink/ukb_v3_chr{chrom}.downsampled10k`. How were these files generated?

**Comment by hammer** [comment]
Thanks @edm1! I often see 1000 Genomes data used for LD reference computation. Is there a reason to prefer the UK Biobank data for this use case?

**Comment by edm1** [comment]
In my experience 1000 Genomes is not sufficiently sized to use for summary stat-based conditional analysis (using GCTA-cojo).

LD calculation from 1000G is fine as an estimate, but will lead to inaccuracies in downstream analyses, i.e. fine mapping. You will see strange results eg. variants that were not nominally significant before conditional analysis end up being highly significant after.

**Comment by hammer** [comment]
Ah, I did not realize LD computed from the ~2.5k individuals in 1000G does not perform well for this task. It would be interesting to quantify the change in performance for different populations!

I found [Prospects of Fine-Mapping Trait-Associated Genomic Regions by Using Summary Statistics from Genome-wide Association Studies](https://www.ncbi.nlm.nih.gov/pubmed/28942963) (2017) which tries to quantify the performance loss but this reference seems to focus more on sample representativeness rather than size.

Another publication uses ~32k samples from Haplotype Reference Consortium (HRC): [Examining the Impact of Imputation Errors on Fine-Mapping Using DNA Methylation QTL as a Model Trait](https://www.ncbi.nlm.nih.gov/pubmed/31040117) (2019). It appears that ~11k of these samples are available from EGA at [EGAD00001002729](https://www.ebi.ac.uk/ega/datasets/EGAD00001002729). Do you have a sense of how this population compares to the UK Biobank sample you use?

**Comment by edm1** [comment]
Whilst the overall sample size of 1000G is ~2.5k it is much smaller for individual sub-populations. Sub-populations would have to be used to get good representativeness.

Early on I enquired about using HRC for conditional analysis. It is only intended for genotype imputation and other uses are not permitted. Chundru _et al._ are comparing the effect of different imputation panels.

**Comment by hammer** [comment]
> Early on I enquired about using HRC for conditional analysis. It is only intended for genotype imputation and other uses are not permitted.

Are other uses not permitted because of the data access committee or because of some technical feature of the sample that makes it not useful for the conditional analysis task?

**Comment by edm1** [comment]
The data access committee
