### ISSUE TITLE
L2G data release via genetics portal

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#408]
This is a ticket to keep track of all proposed changes to display locus-to-gene scores in the genetics portal. ([as disccussed 16 Sept 2019](https://docs.google.com/document/d/15AEBK0356RZxwMwXABUfUGybmo4TwHk2urJ9sVooWWc/edit)).

Data: ~#415 #410~

Back-end: ~#409~ #419 

API: ~#412~

Front-end: #411 #413 #414 #420

**Comment by edm1** [comment]
Here are the latest mock-ups with comments from @andrewhercules https://drive.google.com/open?id=1tSGegDmAiJxErLJPxKq3wZA_7jjUHZWL

**Comment by mkarmona** [comment]
@andrewhercules @edm1 @mirandaio @LucaFumis I already deployed on dev the requested updates to deliver the new changes related to locus to gene feature. Please [see here](https://github.com/opentargets/genetics/issues/412#issuecomment-575170788)

**Comment by andrewhercules** [comment]
Ticket closed as L2G data integrated into Genetics Portal in February 2020 release
