### ISSUE TITLE
L2G FE changes for Study page

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#411]
Changes:
- Replace ‘Top V2G Genes’ with L2G ‘Prioritised genes’ (any gene with prioritised score > 0.5).
- Keep ‘Top Colocalising Genes’ column.
- Change column name of Colocalisation page to ‘Gene Prioritisation’ page (across site).
- Remove rsID and cytoband

**Comment by d0choa** [comment]
We probably want to consider including a column with the distance-based gene, considering ~50% of the top L2G are going to be empty

**Comment by LucaFumis** [comment]
Hi @edm1, which text do we want to use for the tooltips for the columns L2G, Closest Gene, Colocalisation, and the higher header "Prioritised Genes" ?
Do we want to include links to any documentation?

Cheers

**Comment by edm1** [comment]
L2G: Genes prioritised by our locus-to-gene model with posterior probability ≥ 0.5
Closest gene: The closest gene with the closest transcription start site 
Colocalisation: The list of genes which colocalise at this locus with PP(H4) ≥ 0.95 and log2(H4/H3) ≥ log2(5)

I don't feel a tooltip for the higher header is necessary.

**Comment by edm1** [comment]
Changes discussed 30/1/20:

- [ ] Tooltip for closest gene: "The gene with the closest transcription start site"
- [ ] Tooltip for blue “Gene prioritisation” button: "View gene prioritisation results for this locus"
- [ ] Closest gene column should be using:

```GraphQL
{
  variantInfo(variantId: "1_154453788_C_T") {
    nearestCodingGene {
      id,
      symbol
    }
    nearestCodingGeneDistance
  }
}
```

**Comment by LucaFumis** [comment]
Development work done and code all reviewed.
Will merge once the API work is ready to be deployed.

**Comment by andrewhercules** [comment]
Ticket closed as work completed
