### ISSUE TITLE
L2G FE changes for Gene page

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#413]
- [ ] Discuss table design with @andrewhercules @edm1 
- [ ] Replace Associated studies table with L2G assignment results

**Comment by edm1** [comment]
We could remove fields from the associated studies page. E.g.
- PMID
- rsID
- N cases

**Comment by edm1** [comment]
Changes discussed 30/1/20:

- [ ] Rank by L2G score descending
- [ ] Change header “Associated studies” to “Associated studies: locus-to-gene pipeline"
- [ ] Change header “Colocalising studies” to “Associated studies: Colocalisation analysis"
- [ ] There should be no greyed out “Gene prioritisation” buttons
- [ ] Remove "(L2G pipeline)" from “Gene prioritisation” buttons
- [ ] Tooltip for blue “Gene prioritisation” button: "View gene prioritisation results for this locus"
- [ ] Tooltip for “L2G pipeline score” column header "Evidence linking {gene} to this study via our locus-to-gene pipeline. Score range [0, 1]."
- [ ] Column header "Distance to locus" to "Distance to locus (bp)"
- [ ] Column "Distance to locus" to use comma for a thousands separator, e.g. 1341234 to 1,341,234

**Comment by LucaFumis** [comment]
The last two points on "Distance to locus" should be for the new table on study-locus: there's no "distance to locus" on gene page tables, right?

**Comment by edm1** [comment]
Yes thats correct. I added them to the wrong ticket.

**Comment by LucaFumis** [comment]
👍 And thank you for adding all the notes to the tickets yesterday @edm1 !

**Comment by LucaFumis** [comment]
Development work done and code all reviewed.
Will merge once the API work is ready to be deployed.
