### ISSUE TITLE
L2G FE changes for Study-locus page

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#414]
- [ ] Discuss table design with @andrewhercules @edm1 
- [ ] Put L2G Table at the top. All genes at locus with their associated scores (no threshold). Hover over to get raw logi and logo scores (5 individual + overall).
- [ ] Move gene bar upward on colocalisation page (cosmetic: FE only)

**Comment by edm1** [comment]
Need to make sketch of this table and discuss API query

**Comment by edm1** [comment]
Changes discussed 30/1/20:

- [ ] Change header "New stuff goes here..." to “Gene prioritisation using locus-to-gene pipeline"
- [ ] Subtitle change "With some more details on Maternal history of Alzheimer's disease (Marioni RE, 2018) here?" to "Which genes were prioritised by L2G pipeline at this locus?"
- [ ] Change header "QTL Colocalisation" to “Gene prioritisation using colocalisation analysis"
- [ ] Tooltip for “Overall L2G score” column header "Overall evidence linking {gene} to this study using all features. Score range [0, 1]."
- [ ] Tooltip for “Variant pathogenicity” column header "Evidence linking {gene} to this study including variant pathogenicity features only. Score range [0, 1]."
- [ ] Tooltip for “Distance” column header "Evidence linking {gene} to this study including distance features only. Score range [0, 1]."
- [ ] Tooltip for “QTL coloc” column header "Evidence linking {gene} to this study including molecular trait colocalisation features only. Score range [0, 1]."
- [ ] Tooltip for “Chromatin interaction” column header "Evidence linking {gene} to this study including chromatin interaction features only. Score range [0, 1]."

    * Ditto, tooltips for score columns
    * Distance “bp” and comma

**Comment by LucaFumis** [comment]
If last comment https://github.com/opentargets/genetics/issues/413#issuecomment-580382971 is correct, then these apply here:

- [ ]  Column header "Distance to locus" to "Distance to locus (bp)"
- [ ]  Column "Distance to locus" to use comma for a thousands separator, e.g. 1341234 to 1,341,234

**Comment by LucaFumis** [comment]
Development work done and code all reviewed.
Will merge once the API work is ready to be deployed.

**Comment by andrewhercules** [comment]
Ticket closed as work completed
