### ISSUE TITLE
Minor FE variant page changes for L2G release

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#420]
Variant page:
- [ ] Promoter capture HiC in the V2G table will now come from Jung 2019, not Javierre 2016

**Comment by LucaFumis** [comment]
Had a quick look at this: to my understanding those columns details come from the API response `genesForVariantSchema.intervals` ?

**Comment by edm1** [comment]
Yes. However, I've just realised this ticket will need to wait until the new data has been loaded into the backend (#419).

**Comment by andrewhercules** [comment]
Ticket closed as work completed for February 2020 release
