### ISSUE TITLE
Study locus page error/crashes when there are no results

### ISSUE THREAD

**Issue by BjornWouters** [opentargets/genetics#421]
When the study locus page is loaded with a URL that has no data, it crashes instead of returning empty tables. 

**For example an unknown study:** 
https://genetics.opentargets.org/study-locus/UNKNOWN/1_109274968_G_T

In this case the frontend will return the following error:
```
TypeError: "v is null"
    value StudyLocusPage.js:339

```

**Or when a variant is loaded without having L2G data, for example:**
https://genetics.opentargets.org/study-locus/GCST002222/1_109274968_G_A

If a variant with no data is loaded, the following frontend error will be returned:
```
TypeError: "j is null"
    value StudyLocusPage.js:391
```

My guess is that somewhere, the GraphQL error handling is not done properly on this page.

Thanks!

**Comment by mkarmona** [comment]
thanks @BjornWouters  for filling this issue. From the api, [it comes as null](https://tinyurl.com/s6fmor4) and it is a probable case. Regarding the UNKNOWN, may I know how you got to that url? thanks!

**Comment by BjornWouters** [comment]
Thanks for the fast response @mkarmona. The uknown study identifier was just used as an example, there are no studies in Open Targets Genetics having that identifier.

Even though it is an unlikely situation that a study does not contain L2G data, I think handling a error for that would increase the UX for that page.

**Comment by andrewhercules** [comment]
@BjornWouters, we just had a quick chat about this during our weekly team meeting and @mirandaio will investigate further

cc @Sjoerd-van-Hagen

**Comment by andrewhercules** [comment]
Ticket has been removed from the v6 release; instead, it will be part of a broader refactor to implement error boundaries to catch errors without crashing the entire application.

**Comment by ktsirigos** [comment]
work completed
