### ISSUE TITLE
Study beta values have some unexpected results

### ISSUE THREAD

**Issue by BjornWouters** [opentargets/genetics#425]
The study beta column in the GWAS study coloc table sometimes contain values that do not correspond with the original study beta values. For example:

https://genetics.opentargets.org/study-locus/NEALE2_21002_raw/19_44921921_G_A
GCST002222 | LDL cholesterol | Willer CJ | 19_44908822_C_T | 0.0

This row has a beta value of 0 whilst the variant on the study page has a beta of -0.59. 

https://genetics.opentargets.org/study-locus/GCST002222/19_44886339_G_A
NEALE2_21002_raw | Weight | UKB Neale v2 | 19_44921921_G_A | 0.56

This row has a beta value of 0.56 whilst the variant on the study page has a beta of 0.50.

https://genetics.opentargets.org/study-locus/GCST002222/19_44886339_G_A

GCST005923 | Maternal history of Alzheimer's disease | Marioni RE | 19_44905307_A_T | -0.093

This row has a beta value of -0.093 but the original study does not have beta values, only odds ratio's. 

What is the reason that these values do not correspond with the beta values on the study page? 

Thanks!

**Comment by andrewhercules** [comment]
Hi @BjornWouters! We've recently added a note to our docs about this - see https://genetics-docs.opentargets.org/faqs#why-are-betas-and-odds-ratios-displayed-inconsistently-in-the-portal for more information. Does that help?

**Comment by BjornWouters** [comment]
@andrewhercules  Not exactly. I am referring to the betas in the coloc table. These should be similar as those on the study page am I right?

**Comment by andrewhercules** [comment]
Ahh okay let me investigate - I'll check our team Google Drive to see if I can find any references to that - will let you know 👍

**Comment by MayaGhoussaini** [comment]
Hello @BjornWouters and @andrewhercules ! The reason you're seeing this, is because the beta we're displaying in the coloc table corresponds to the beta of the lead variant at the top of the page rather than the individual variants shown for each of the rows. The reason we decided to do it this way is so the user can compare the direction of effect across the different colocalising tissues. Hope this helps.

**Comment by andrewhercules** [comment]
Thank you @MayaGhoussaini!

**Comment by deniseOme** [comment]
Thanks @BjornWouters for raising this question and @MayaGhoussaini for providing a detailed explanation. We will be turning your query into a [FAQ](https://genetics-docs.opentargets.org/faqs) for the Open Targets Genetics docs in case other users wonder the same.

**Comment by andrewhercules** [comment]
Ticket closed as Genetics Portal docs will be updated as noted in #426
