### ISSUE TITLE
links to Ensembl GRCh37 and UniProt search page

### ISSUE THREAD

**Issue by deniseOme** [opentargets/genetics#427]
From a gene page like this https://genetics.opentargets.org/gene/ENSG00000169174, we link out to Ensembl GRCh37 (https://grch37.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000169174;r=1:55505221-55530525) whereas the coordinates for the gene on the very same page in OTG are on GRCh38.

To avoid confusion and to be consistentn we should link to https://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000169174;r=1:55039447-55064852 instead.

Similar issue observed in the variant page has been fixed by @mirandaio. See #393 

Note that the UniProt link in the same gene page of Open Targets Genetics (e.g. https://genetics.opentargets.org/gene/ENSG00000169174) would benefit from a refined choice of landing page as currently takes us to https://www.uniprot.org/uniprot/?query=PCSK9&sort=score. This landing page shows results of the search for PCSK9, which includes other proteins than human.

Would there be any chance to link to this page instead?
https://www.uniprot.org/uniprot/Q8NBP7
(the actual human target).

Or at least make the call to UniProt using the Ensembl Gene ID rather than the gene symbol? The latter will return human, mouse, rat, other vertebrates, whereas the former will return just the human protein:
https://www.uniprot.org/uniprot/?query=ENSG00000169174&sort=score

**Comment by andrewhercules** [comment]
Can we please adjust the link to Ensembl on the gene page? Please remove the `.grch37` from the URL template.

**Comment by ktsirigos** [comment]
closing this one as work is done.
