### ISSUE TITLE
GraphQL endpoint `studiesForGene` does not work

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/genetics#432]
Given an gene with associated studies (eg. *ENSG00000012048 - BRCA1 *) when I execute a valid GraphQL query I receive an empty array, rather than an array of studies. 

GraphQL query: 
```
query gene {
  studiesForGene(geneId: "ENSG00000012048"){
    study {
      pmid
      pubDate
      pubJournal
      pubTitle
    }
  }
}
```
Observed result:
```
{
  "data": {
    "studiesForGene": []
  }
}
```
Expected result: 

An array with the studies listed here: https://genetics.opentargets.org/gene/ENSG00000012048

Log output from gcloud:

https://console.cloud.google.com/logs/viewer?resource=gce_instance%2Finstance_id%2F4752898940362486575&project=open-targets-genetics&authuser=0&supportedpurview=project&minLogLevel=0&expandAll=false&timestamp=2020-07-16T07%3A44%3A27.553000000Z&customFacets&limitCustomFacetWidth=true&dateRangeStart=2020-07-16T06%3A44%3A27.806Z&dateRangeEnd=2020-07-16T07%3A44%3A27.806Z&interval=PT1H&scrollTimestamp=2020-07-16T07%3A23%3A40.812685084Z&advancedFilter=resource.type%3D%22gce_instance%22%0Aresource.labels.project_id%3D%22open-targets-genetics%22%0Aresource.labels.instance_id%3D%224752898940362486575%22%0Aresource.labels.zone%3D%22europe-west1-d%22%0Atimestamp%3D%222020-07-16T07%3A23%3A40.812685084Z%22%0AinsertId%3D%22qd4ok9f7vckky%22

**Comment by JarrodBaker** [comment]
@d0choa @mkarmona : I'm assuming the endpoint this bug relates to is currently not used by neither our front end or users (who would have noticed they get no results). Do we want to fix this feature or remove it?

**Comment by mkarmona** [comment]
Good you saw that. @JarrodBaker i would remove it as there is another one that gives the needed info for a gene too. Thanks!
