### ISSUE TITLE
Fix link in "Evidence of colocalisation” column

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/genetics#438]
In the "Gene prioritisation using locus-to-gene pipeline" table on the gene prioritisation page (e.g. [LDL cholesterol + locus around 19_44908822_C_T](https://genetics.opentargets.org/study-locus/GCST002222/19_44908822_C_T)), there is a column called "Evidence of colocalisation".

Within the column, if the value is "Yes" (based on the `hasCololc` response from the API), it links the user to the "GWAS Study Colocalisation" table.

![Screenshot 2021-03-12 at 09 47 57](https://user-images.githubusercontent.com/7490258/110923047-5dbc3000-8318-11eb-8006-22218b9c1a0a.png)

However, upon review by @Jeremy37, this is a bug and instead, the "Yes" link to should direct users to the "Gene prioritisation using colocalisation analysis" table on the same page.

**Comment by ktsirigos** [comment]
closing this one as work is done.
