### ISSUE TITLE
should the summary stats be filtered?

### ISSUE THREAD

**Issue by elipapa** [opentargets/genetics#44]
should the data we serve be somewhat filtered?

while we need the full data for finemapping and coloc, we may not need the non-significant data for regional plot + phewas?

it would help the database/backend to deal with less points.

**Comment by edm1** [comment]
I just discussed this with @MayaGhoussaini. Non-significant associations can be interesting from a drug development point of view.

Non-significant associations in well-powered study (large sample size) can be considered negative evidence. This would be important for the PheWAS analysis. On the other hand, I don't think p>0.05 associations are important for the regional plot.

At some point in the future we could calculate log(approximate Bayes factors) for each variant (requires: sample size, effect allele frequency, case-control proportion).
- log(BF) > 0 is positive evidence of association
- log(BF) < 0 is negative evidence
- log(BF) ≈ 0 is not informative and could be discarded

**Comment by elipapa** [comment]
cc @mkarmona
