### ISSUE TITLE
Update genetics-app dependencies

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/genetics#445]
A number of dependabot PRs have been opened in [genetics-app](https://github.com/opentargets/genetics-app/pulls).

Can we please update all relevant dependencies?

**Comment by ktsirigos** [comment]
will be doing all repo dependencies this week

**Comment by ktsirigos** [comment]
there are quite a few 'high severity' ones

**Comment by andrewhercules** [comment]
@mirandaio can you also please update the dependencies for the following repos used by the Genetics Portal?

- https://github.com/opentargets/ot-ui/
- https://github.com/opentargets/ot-charts when doing the

**Comment by ktsirigos** [comment]
closing this one as work is done.
