### ISSUE TITLE
Update footer style and content

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/genetics#446]
Can we please change the current Genetics Portal footer to match the footer used in the Platform?

![Screenshot 2021-06-07 at 10 24 53](https://user-images.githubusercontent.com/7490258/120992543-9da97c80-c77a-11eb-8653-fa462fc7b0df.png)

There are two minor changes we should make:

1. In the "About" column, change "Platform" to "Genetics Portal" and use the existing version and commit content
2. In the "Help" column, change the "Documentation" link to `https://genetics-docs.opentargets.org/`

**Comment by ktsirigos** [comment]
closing this one as work is done.
