### ISSUE TITLE
Update navigation bar links

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/genetics#448]
Can we please change the navigation bar links?

| Text | Link |
| --- | --- |
| Documentation | `https://genetics-docs.opentargets.org/` | 
| Data downloads | `https://genetics-docs.opentargets.org/data-access/data-download` | 
| API | `https://genetics-docs.opentargets.org/data-access/graphql-api` |
| Community | `http://community.opentargets.org/` | 
| Contact us | `mailto:helpdesk@opentargets.org` |

**Comment by ktsirigos** [comment]
closing this one as work is done.
