### ISSUE TITLE
Update PheWAS plot with drop-down to filter for specific biobank/source

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/genetics#452]
Currently the PheWAS plot on the variant page contains information on the variant in both UK Biobank and GWAS Catalog. 

![Screenshot 2021-06-10 at 16 04 14](https://user-images.githubusercontent.com/7490258/121549334-ae215780-ca05-11eb-844f-b5fd53ab4899.png)

With the inclusion of FinnGen data in our next release, this plot will see an increased number of points.

Can we please do the following?

- [x] Update the description to read:

> Which traits are associated with this variant in the UK Biobank, FinnGen, and/or GWAS Catalog summary statistics repository? Only traits with P-value < 0.05 are returned.

- [x] Add a drop-down filter that allows users to view the following options
- "FinnGen, UK Biobank, and GWAS Catalog"
- "FinnGen"
- "UK Biobank"
- "GWAS Catalog" 

Please note that this ticket requires updates that should be available in the development API (once available).

**Comment by andrewhercules** [comment]
In order to filter the source of the data, you can use the `studyInfo.source` field that returns the following values:

Value from API | Mapped source |
| --- | --- |
| `FINNGEN` | FinnGen |
| `SAIGE` | UK Biobank |
| `NEALE2` | UK Biobank |
| `GCST` | GWAS Catalog |

As noted in the above table, both `NEALE2` and `SAIGE` studies will need to be included in the plot if a user selects the `UK Biobank` dropdown option.

**Comment by ktsirigos** [comment]
closing this one as work is done.
