### ISSUE TITLE
Update homepage

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/genetics#456]
- [ ] Remove the SVG

- [ ] Add a new section called "Get started with the Genetics Portal", similar to the homepage for the Platform. (see https://github.com/opentargets/platform/issues/1448)

![Screenshot 2021-06-11 at 13 04 06](https://user-images.githubusercontent.com/7490258/121683626-8db0d600-cab5-11eb-85df-1e2d6cb9b902.png)

| FontAwesome icon | Link | Text |
| --- | --- | --- |
| [download](https://fontawesome.com/icons/download?style=solid) | `https://genetics-docs.opentargets.org/data-access/data-download` | Download all of our datasets |
| [laptop-code](https://fontawesome.com/icons/laptop-code?style=solid) | `https://genetics-docs.opentargets.org/data-access/graphql-api` | Access data with our GraphQL API  |
| [question-circle](https://fontawesome.com/icons/question-circle?style=solid) | `https://genetics-docs.opentargets.org/` | Check out our Platform documentation |
| [file-alt](https://fontawesome.com/icons/file-alt?style=regular) | `https://genetics-docs.opentargets.org/citation` | Read our latest Platform publications |
| [comment-dots](https://fontawesome.com/icons/comment-dots?style=regular) | `https://community.opentargets.org/` | Join the Open Targets Community |

**Comment by andrewhercules** [comment]
Ticket removed from `v6` release and rescoped for technical release scheduled in January/February 2022

**Comment by ktsirigos** [comment]
work completed
