### ISSUE TITLE
Not possible to search by finngen study id FINNGEN_R5_AD_LO

### ISSUE THREAD

**Issue by d0choa** [opentargets/genetics#459]
@Jeremy37 reported it's currently not possible to search by the next finngen study (FINNGEN_R5_AD_LO), despite the study page existing https://dev--genetics-app.netlify.app/study/FINNGEN_R5_AD_LO

**Comment by mirandaio** [comment]
This search term causes an internal server [error](https://open-targets-genetics-dev.ew.r.appspot.com/graphql/browser?query=query%20%7B%0A%20%20search(queryString%3A%20%22FINNGEN_R5_AD_LO%22)%20%7B%0A%20%20%20%20studies%20%7B%0A%20%20%20%20%20%20studyId%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

**Comment by d0choa** [comment]
#463 might be causing this issue
