### ISSUE TITLE
Update deployment configuration to set Google Tag Manager ID

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/genetics#461]
Can we please set a deployment configuration variable for our Genetics Portal GTM ID?

`GTM-PNQWZ2V`

**Comment by mbdebian** [comment]
Hi @mirandaio , as soon as you have an input parameter for this in the react application, I can add the information to the deployment context.
Thanks!

**Comment by mirandaio** [comment]
Hi @mbdebian a deployment parameter has been added to configure the GTMID https://github.com/opentargets/genetics-app/blob/main/public/config.template#L3

**Comment by mbdebian** [comment]
Noted!, I have added (commented) the parameter to the development deployment context, I'll use the value provided by @andrewhercules for the deployment in production.

**Comment by mbdebian** [comment]
Done ^_^
