### ISSUE TITLE
Internal server error when comparing studies

### ISSUE THREAD

**Issue by d0choa** [opentargets/genetics#465]
As reported by @Jeremy37, the compare studies page returns an internal server error for this study:
https://dev--genetics-app.netlify.app/study-comparison/NEALE2_30190_raw

I narrowed down the query that fails:

- This works:

```
query TopOverlappedStudiesQuery{
  topOverlappedStudies(studyId: "NEALE2_30190_raw") {
    topStudiesByLociOverlap {
      numOverlapLoci
    }
  }
}

```

- This doesn't work [[full query link](https://open-targets-genetics-dev.ew.r.appspot.com/graphql/browser?query=query%20TopOverlappedStudiesQuery%7B%0A%20%20topOverlappedStudies(studyId%3A%20%22NEALE2_30190_raw%22)%20%7B%0A%20%20%20%20topStudiesByLociOverlap%20%7B%0A%20%20%20%20%20%20numOverlapLoci%0A%20%20%20%20%20%20study%20%7B%0A%20%20%20%20%20%20%20%20studyId%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=TopOverlappedStudiesQuery)]:

```
query TopOverlappedStudiesQuery{
  topOverlappedStudies(studyId: "NEALE2_30190_raw") {
    topStudiesByLociOverlap {
      numOverlapLoci
      study {
        studyId
      }
    }
  }
}

```

**Comment by mkarmona** [comment]
study table needs to be recomputed again.

**Comment by d0choa** [comment]
Confirming the issue is fixed in dev and causes no issues to FE

**Comment by d0choa** [comment]
Now a different study produces the internal server error [Query link](https://open-targets-genetics-dev.ew.r.appspot.com/graphql/browser?query=query%20TopOverlappedStudiesQuery%7B%0A%20%20topOverlappedStudies(studyId%3A%20%22GCST004131%22)%20%7B%0A%20%20%20%20topStudiesByLociOverlap%20%7B%0A%20%20%20%20%20%20numOverlapLoci%0A%20%20%20%20%20%20study%20%7B%0A%20%20%20%20%20%20%20%20studyId%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=TopOverlappedStudiesQuery):

```
query TopOverlappedStudiesQuery{
  topOverlappedStudies(studyId: "GCST004131") {
    topStudiesByLociOverlap {
      numOverlapLoci
      study {
        studyId
      }
    }
  }
}
```
