### ISSUE TITLE
When I search for amyotrophic lateral sclerosis in the genetics portal, I get this - top study showing 37 loci

### ISSUE THREAD

**Issue by mkarmona** [opentargets/genetics#476]
![image (1)](https://user-images.githubusercontent.com/5394232/126348041-3cabe6b2-d84e-43a0-a2eb-982e32775d99.png)

**Comment by mohdkarim** [comment]
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/30321499/126350432-770c8ffe-5187-48f3-ba4a-fe836107356f.png">

COVID-19 phenotype (likely any case vs. population controls) are not labelled.

**Comment by Jeremy37** [comment]
Just to note that the bug is that the number of loci differs when you see the study in the search box vs. when you actually get to the study page.

**Comment by Jeremy37** [comment]
Seems to be fixed... though there are still sometimes discrepancies in number of loci shown, which I will record in a separate issue.
