### ISSUE TITLE
transfer cleaned uk biobank summary stats to a structured bucket

### ISSUE THREAD

**Issue by elipapa** [opentargets/genetics#50]
to match the structure detailed at: https://docs.google.com/document/d/18splDAKSlboKCQdAcLogexE_Zd3odv6qlTSPoBUI4aQ/edit

**Comment by edm1** [comment]
Structured Neale et al UKB summary stats version 1 are now located in `gs://genetics-portal-sumstats/gwas/genome_wide/{study id}/{trait code}/{chromosome}-{study id}-{trait code}.tsv.gz`.

@mkarmona These files supersede the summary stats I have previously sent you instructions for. Information about the fields contained within these files can be found here: https://github.com/opentargets/sumstat_data. I'll go through this with you at some point.
