### ISSUE TITLE
A specific genetics portal study-locus page fails to show

### ISSUE THREAD

**Issue by Jeremy37** [opentargets/genetics#509]
This page for the CARD9 locus in de Lange IBD starts loading and then just shows as blank:
https://main--genetics-app.netlify.app/study-locus/GCST004131/9_136374746_A_G

**Comment by andrewhercules** [comment]
@carcruz can you please investigate this issue?

**Comment by andrewhercules** [comment]
Ticket closed as work completed and merged into `v6` release
