### ISSUE TITLE
move pqtl summary stats to bucket

### ISSUE THREAD

**Issue by elipapa** [opentargets/genetics#51]

**Comment by edm1** [comment]
The pQTLs need harmonising (alleles are not aligned/consistent with the reference). This means we're currently losing a lot of info in the V2G pQTL data.

I'll hack something together now but this won't be finished until next week.

**Comment by edm1** [comment]
pQTLs are harmonised and uploaded to `gsutil ls gs://genetics-portal-sumstats/molecular_qtl/pqtl/SUN2018/UBERON_0001969`
