### ISSUE TITLE
Colocalisation sometimes fails at loci with p < ~1e-308

### ISSUE THREAD

**Issue by Jeremy37** [opentargets/genetics#524]
Kaur pointed out that there should be a colocalisation between ARGHEF3 in the CEDAR eQTL dataset and platelet count GWAS, which can both be fine-mapped to a single causal variant at the locus.

I looked into this, and one problem is that the coloc pipeline uses p values for SNPs as input:
https://github.com/opentargets/genetics-colocalisation/blob/master/scripts/coloc.R
But it should use beta/se if those are available.
When SNP p values are as small as can be represented in a float, then all are given p = ~1e-308, and thus many SNPs are (incorrectly) treated as having the same association statistic. This means that the eQTL study has a single variant in its credible set (3_56815721_T_C) with prob > 0.999. This same variant should be fine-mapped in the GWAS, but instead many SNPs are given the same (fairly low) probability.

There is something else strange at this locus, however. The output of our coloc analysis gives about 70% probability to coloc hypothesis H1 - that there is a causal variant in the GWAS and not in the eQTL study, which is strange since tag_pcond =~ 1e-16 for the eQTL.

**Comment by MayaGhoussaini** [comment]
Thanks Jeremy. That is useful. In that case, can we change the pipeline and ask it to preferentially use beta and std error rather than p-values when these are available? Thanks

**Comment by Jeremy37** [comment]
Needs to be checked, but this should be fixed in the upcoming release.

**Comment by Jeremy37** [comment]
Looks like this is fixed in the new release.
