### ISSUE TITLE
Teslovich TM (2010) - flipped betas

### ISSUE THREAD

**Issue by mohdkarim** [opentargets/genetics#525]
We report sumstats from Teslovich TM (2010) for 4 traits (Triglycerides, total cholesterol, HDL-C, and LDL-C). On comparing the signs of a few of the top variant effect estimates from the study page for each of the four traits, it appears that the beta sign does not correspond to the ALT allele. 

Example: https://genetics.opentargets.org/variant/2_27508073_T_C (rs1260326) reports positive association of C-allele (ALT) with triglycerides when the paper (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3039276/figure/F1/?report=objectonly) reports positive association with the T-allele (REF), so the association with C-allele should be negative. This issue of flipped betas is present for all the variants we report for Teslovich TM (2010) across the four traits in our portal.

**Comment by DSuveges** [comment]
The harmonised summary stats[1] already looks like that:

```
hm_variant_id               2_27508073_T_C
hm_rsid                     rs1260326
hm_chrom                    2
hm_pos                      27508073
hm_other_allele             T
hm_effect_allele            C
hm_beta                     0.1159
hm_odds_ratio               NA
hm_ci_lower                 NA
hm_ci_upper                 NA
hm_effect_allele_frequency  NA
hm_code                     10
variant_id                  rs1260326
other_allele                t
effect_allele               c
p_value                     5.68e-133
beta                        0.1159
standard_error              0.0049
odds_ratio                  NA
chromosome                  2
effect_allele_frequency     NA
ci_lower                    NA
ci_upper                    NA
```

[1] ftp://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST000001-GCST001000/GCST000758/harmonised/20686565-GCST000758-EFO_0004530.h.tsv.gz

**Comment by buniello** [comment]
I will take a look and filp betas if needed

**Comment by buniello** [comment]
Summary statistics with reviewed beta direction have now been released for Teslovich TM (2010) for 4 traits (Triglycerides, total cholesterol, HDL-C, and LDL-C).
https://www.ebi.ac.uk/gwas/publications/20686565

**Comment by d0choa** [comment]
This issue has been fixed in the development branch and it will be available in production in the upcoming portal release.

I'm closing the issue, but please @Jeremy37 report if there are any further actions required to prevent us from flipping the betas again now that they have been fixed at the source. Thank you @buniello for the fix

<img width="1634" alt="Screenshot 2022-02-22 at 12 11 09" src="https://user-images.githubusercontent.com/5097586/155130670-aef9f3f1-b587-4659-9417-78cb319ef19f.png">
