### ISSUE TITLE
Manhattan plot

### ISSUE THREAD

**Issue by peatroot** [opentargets/genetics#53]
The Manhattan plot will be embedded within the study page.

## Minimal API
Below is the subset of the graphql schema relevant to this plot. Until such time as the actual API gives full support, front-end will mock against this schema.
```
type Query {
    studyInfo(studyId: String!): StudyInfo
    manhattan(studyId: String!): Manhattan
}
type StudyInfo {
    studyId: String!
    traitReported: String!
    pubAuthor: String
    pubDate: String
    pubJournal: String
    pmid: String
}
type Manhattan {
    associations: [ManhattanAssociation!]!
}
type ManhattanAssociation {
    # the fields below are critical to the plot
    variantId: String!
    variantRsId: String
    pval: Float!
    chromosome: String!
    position: Int!

    # the fields below need to be shown within the table and/or tooltips
    bestGenes: [Gene!]
    credibleSetSize: Int
    ldSetSize: Int
    totalSetSize: Int
}
type Gene {
    id: String
    symbol: String
}
```

## Design
The key features that need to be supported are:
* chart
  * svg download
  * tooltip with row content
  * zoom in/out on chromosome
  * highlight on mouseover
* table
  * csv/tsv download
  * sorting by any column
  * infinite scroll or pagination

Below are mock-ups of the plot and table.
![Screen Shot 2018-07-31 at 13.59.53.png](https://images.zenhubusercontent.com/59565b4461b4ca3b0a72d36a/4ed97f24-0161-4819-9566-827dec16b2ea)
![Screen Shot 2018-07-31 at 14.00.19.png](https://images.zenhubusercontent.com/59565b4461b4ca3b0a72d36a/7b907de2-52fa-4008-b65a-02a5ab529b04)

**Comment by peatroot** [comment]
@opentargets/genetics, can you please take a look at https://admiring-dubinsky-cb7f95.netlify.com/study/GCST005806 and comment on the following:
* Are the column names correct?
* What should the help text be in each column (there will be a pop-up tooltip)?
* Are we missing anything?

**Comment by edm1** [comment]
Additional data for top of page:
- Trait name
- Publication information
  - Author et al (2017)
  - Journal name
  - PMID
- Number of loci with genome-wide significance (number of rows in table where p<5e-8)

- Associated loci = 'Independently-associated loci'
- No subtitle

Column names:
- indexVariant = 'Lead Variant'
- indexVariantRsid = 'rsID'
- pval = 'P-value'
- ldSetSize = 'LD Set Size'
  - tooltip = 'Number of variants that are in LD (R2 >= 0.7) with this lead variant'
- credibleSetSize = 'Credible Set Size'
  - tooltip = 'Number of variants in 95% credible set at this locus'

Additional columns that may be useful:
- Best guess gene (from V2G)
- Cytoband (lower priority, we'll need to look at how to produce this info)
- Minor allele frequency (lower priority but very useful). Could come from Ensembl API or we will need to produce a variant table ourself.

On the plot:
- Genome-wide significance line at 5e-8

Table behaviour:
- Clicking on chromosome in plot filters rows in table for same chromosome
- Possible to sort variant_id by [1...22, X]?
- Deafult sort pvalue ascending

**Comment by mkarmona** [comment]
@peatroot @mirandaio studyinfo as defined (few changes and additions too). If there is no studyid info then null will be returned

```
"This element contains all study fields"
type Study {
  "Study Identifier"
  studyId: String!

  "Trait Identifier"
  traitCode: String!

  "Trait Label as reported on the publication"
  traitReported: String!

  "A list of curated efo codes"
  traitEfos: [String!]!

  "Publication ID"
  pubId: String

  "Publication Date as YYYY-MM-DD"
  pubDate: String

  "Publication Journal name"
  pubJournal: String

  "Publication Title"
  pubTitle: String

  "Publication author"
  pubAuthor: String
}
```
I will take a few minutes in order to be deployed

**Comment by mkarmona** [comment]
@peatroot @mirandaio, as we discussed in the case of multiple indexers' publication identifiers, you are right on we have to have multiple fields one each per indexer. Here the updated graphql schema

```
"This element contains all study fields"
type Study {
  "Study Identifier"
  studyId: String!

  "Trait Identifier"
  traitCode: String!

  "Trait Label as reported on the publication"
  traitReported: String!

  "A list of curated efo codes"
  traitEfos: [String!]!

  "PubMed ID for the corresponding publication"
  pmid: String

  "Publication Date as YYYY-MM-DD"
  pubDate: String

  "Publication Journal name"
  pubJournal: String

  "Publication Title"
  pubTitle: String

  "Publication author"
  pubAuthor: String
}
```
