### ISSUE TITLE
Gecko plot

### ISSUE THREAD

**Issue by peatroot** [opentargets/genetics#54]
The Gecko plot will be embedded within its own page, which is parameterised by chromosome, start and end.

## Minimal API
Below is the subset of the graphql schema relevant to this plot. Until such time as the actual API gives full support, front-end will mock against this schema.
```
type Query {
    # TBD
    locus(chromosome: String, start: Int, end: Int, ...): Locus
    locusTable(chromosome: String, start: Int, end: Int, ..., offset: Int, limit: Int): LocusTable
}
type Locus {
    # TBD
}
type LocusTable {
    # TBD
}
```
See [the graphql schema](https://github.com/opentargets/postgap-api/blob/master/src/schema.gql) of postgap.opentargets.io for inspiration.

## Design
The key features that need to be supported are:
* chart
  * svg download
  * highlight on click
  * pan/zoom with buttons and/or mouse interactions
* table
  * csv/tsv download
  * sorting by any column
  * infinite scroll or pagination (will likely need server side pagination)
* filters (TBD)

Below is a screenshot of postgap.opentargets.io, which we should take inspiration from.
![Screen Shot 2018-07-31 at 14.52.18.png](https://images.zenhubusercontent.com/59565b4461b4ca3b0a72d36a/308bba84-68eb-4f69-b088-8289be7ad07d)

**Comment by peatroot** [comment]
Below is a draft of the schema for the gecko plot, following discussion with @mkarmona and @edm1. It will likely need to be iterated as we add tooltips and filters, but should be sufficient for a first rendering.
```
type query {
  gecko(chromosome: String!, start: Int!, end: Int!): Gecko!
}
type Gecko {
  genes: [Gene!]!
  tagVariants: [TagVariant!]!
  indexVariants: [IndexVariant!]!
  studies: [Study!]!
  geneTagVariants: [GeneTagVariant!]!
  tagVariantIndexVariantStudies: [TagVariantIndexVariantStudy!]!
}
type Gene {
  id: String!
  symbol: String!
  forwardStrand: Boolean!
  exons: [[Int!]!]!
}
type TagVariant {
  id: String!
  rsId: String
  position: Int!
}
type IndexVariant {
  id: String!
  rsId: String
  position: Int!
}
type Study {
  studyId: String!
  traitReported: String!
  pubAuthor: String
  pubDate: String
  pubJournal: String
  pmid: String
}
type GeneTagVariant {
  geneId: String!
  tagVariantId: String!
  overallScore: Float!
}
type TagVariantIndexVariantStudy {
  tagVariantId: String!
  indexVariantId: String!
  studyId: String!
  r2: Float
  pval: Float!
  posteriorProbability: Float
}
```

**Comment by peatroot** [comment]
@mkarmona @edm1, can one of you please calculate the number of `TagVariantIndexVariantStudy`'s in a few 2MB windows? Before we commit to the above schema, we should know the magnitude of this field.

**Comment by mkarmona** [comment]
@peatroot a small change and a small improvement
```
type query {
  gecko(chromosome: String!, start: Int!, end: Int!): Gecko!
}
type Gecko {
  genes: [Gene!]!
  tagVariants: [Variant!]!
  indexVariants: [Variant!]!
  studies: [Study!]!
  geneTagVariants: [GeneTagVariant!]!
  tagVariantIndexVariantStudies: [TagVariantIndexVariantStudy!]!
}
type Gene {
  id: String!
  symbol: String!
  forwardStrand: Boolean!
  exons: [Int!]!
}

type Variant {
  id: String!
  rsId: String
  position: Int!
}
type Study {
  studyId: String!
  traitReported: String!
  pubAuthor: String
  pubDate: String
  pubJournal: String
  pmid: String
}
type GeneTagVariant {
  geneId: String!
  tagVariantId: String!
  overallScore: Float!
}
type TagVariantIndexVariantStudy {
  tagVariantId: String!
  indexVariantId: String!
  studyId: String!
  r2: Float
  pval: Float!
  posteriorProbability: Float
}
```
gene.exons is a flatten list of numbers and tagvariants and indexvariants share the same index type of object so I will use the same but duplicated as you specified

**Comment by mkarmona** [comment]
@peatroot the gecko has to be nullable as the string representing the chromosome could be wrong and then all my query gets screwed.

```
type query {
  gecko(chromosome: String!, start: Int!, end: Int!): Gecko
}
type Gecko {
  genes: [Gene!]!
  tagVariants: [Variant!]!
  indexVariants: [Variant!]!
  studies: [Study!]!
  geneTagVariants: [GeneTagVariant!]!
  tagVariantIndexVariantStudies: [TagVariantIndexVariantStudy!]!
}
type Gene {
  id: String!
  symbol: String!
  forwardStrand: Boolean!
  exons: [Int!]!
}

type Variant {
  id: String!
  rsId: String
  position: Int!
}
type Study {
  studyId: String!
  traitReported: String!
  pubAuthor: String
  pubDate: String
  pubJournal: String
  pmid: String
}
type GeneTagVariant {
  geneId: String!
  tagVariantId: String!
  overallScore: Float!
}
type TagVariantIndexVariantStudy {
  tagVariantId: String!
  indexVariantId: String!
  studyId: String!
  r2: Float
  pval: Float!
  posteriorProbability: Float
}
```

**Comment by mkarmona** [comment]
api online and ready to be used
![captura de pantalla -2018-09-05 16-51-21](https://user-images.githubusercontent.com/5394232/45105426-214a6080-b12c-11e8-8faf-dee572ff1e9a.png)

**Comment by peatroot** [comment]
Remaining tasks opened as separate more specific issues, so closing.
