### ISSUE TITLE
Versioning on the Genetics home page

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/genetics#541]
Under "last updated", the Genetics home page currently gives a date-style versioning (22.02). 

<img width="847" alt="Screenshot 2022-02-28 at 17 16 18" src="https://user-images.githubusercontent.com/73692302/156027956-068f98dc-723e-4e46-8958-12b53dd2b157.png">

However, I had previously agreed with the Genetics team to version the releases using a numbering system (version 7). 

@carcruz @d0choa As the numbering system is used in the blog posts, Community, and other external comms, would it be possible to update the Genetics home page to reflect this?

**Comment by d0choa** [comment]
I'm really sorry, but this data comes from the BE. I know this has not been communicated adequately and apologise for this. The change wasn't really planned, but it came out as a result of mimicking the Platform infrastructure for the latest Genetics release. There are several benefits of aligning Platform/Portal release naming conventions and it will become one single release versioning system as both ETLs blend together.

API response:

```
{
    "data": {
        "meta": {
            "dataVersion": {
                "major": 22,
                "minor": 2,
                "__typename": "Version"
            },
            "__typename": "Metadata"
        }
    }
}
```
