### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by peatroot** [opentargets/genetics#58]
There should be a standard search bar on several pages. This should support searching for genes, variants and traits/studies.

## Minimal API
Below is the subset of the graphql schema relevant to the search bar. Until such time as the actual API gives full support, front-end will mock against this schema.
```
type Query {
     search(queryString: String!) Search!
}
type Search {
    results: [SearchResult!]!
}
union SearchResult = GeneSearchResult | VariantSearchResult | StudySearchResult
type GeneSearchResult {
    id: String!
    symbol: String!
    name: String
    synonyms: [String!]!
}
type VariantSearchResult {
    variantId: String!
    rsId: String
}
type StudySearchResult {
    studyId: String!
    reportedTrait: String!
    pubAuthor: String
    pubDate: String
    pubJournal: String
    # TBD: sample size
    # TBD: loci count
}
```

## Design
Below is a mock-up of the search bar with an item selected.
![Screen Shot 2018-07-31 at 15.19.34.png](https://images.zenhubusercontent.com/59565b4461b4ca3b0a72d36a/4021e8cc-12d9-4558-aad2-7dc77d4c7caf)
Below is a mock-up of the search bar when searching for a gene.
![Screen Shot 2018-07-31 at 15.20.21.png](https://images.zenhubusercontent.com/59565b4461b4ca3b0a72d36a/c7fe65b0-2b24-401f-b466-faf601879f59)
Below is a mock-up of the search bar when searching for a variant.
![Screen Shot 2018-07-31 at 15.20.09.png](https://images.zenhubusercontent.com/59565b4461b4ca3b0a72d36a/df807f9e-fae8-480d-9c04-55dd073ad408)
Below is a mock-up of the search bar when searching for a trait.
![Screen Shot 2018-07-31 at 15.19.48.png](https://images.zenhubusercontent.com/59565b4461b4ca3b0a72d36a/84f62d0e-4d83-4ca7-af76-a1ec4290d7e3)

**Comment by mkarmona** [comment]
@peatroot this last update sounds a bit better than the initial one. I like the idea of having more type of independent results based on the query. But, I guess it makes more sense getting similar structured results but a different type of queries as best hits or search or exact match or whatever other queries you may want to ask

**Comment by andrewhercules** [comment]
Can we allow users the search by the following?

**Gene**
- [ ] Ensembl ID (e.g. ENSG00000001626)
- [ ] HGNC symbol (e.g. BRAF)

**Variant**
- [ ] variant ID (e.g. 10 : 114,754,071 T>C)
- [ ] RSID (e.g. rs123)

**Trait**
- [ ] Reported trait (e.g. insulin resistance] *confirm that all rows have a reported trait
- [ ] Study ID (e.g. GCST004773) *confirm what formats of study ID are found in the data
- [ ] PubMed ID (e.g. 28566273) 
- [ ] Author (e.g. McCarthy)*

With the author search, we will need to make it clear that a user can only search by the last name of the first author as the entire list of authors is not be available. This could pose a problem if a user is more familiar with a study conducted by a lab and not the individual researcher.

**Comment by mkarmona** [comment]
@andrewhercules I don't know how to interpret your variant id specs. At the moment, the user can search for a variant id formated as `CHROMOSOME_POSITION_REFALLELE_ALTALLELE`. An example of that format is `10_114754071_T_C`. Do you want me to check if the final form of a variant meets a pattern like the one you specified?

**Comment by andrewhercules** [comment]
I took that format from [PheWeb](http://pheweb.sph.umich.edu/variant/10:114754071-T-C) as I figured that they used a common standard. I noticed that other sites (e.g. [Varsome](https://varsome.com/variant/hg19/10%3A114754071%20T%3EC)) allow for a similar search. But then [ExAC](http://exac.broadinstitute.org/) and [OMIM](https://www.omim.org/) among others are quite different.  

So for the ASHG release, let's stick with your existing format of `10_114754071_T_C`.

@peatroot and @mirandaio, could the front-end allow a user to enter `10 : 114,754,071 T>C` but then convert it to `10_114754071_T_C` before running a search?

**Comment by peatroot** [comment]
@andrewhercules @mkarmona, we could put in a regex for exactly that format, but I'd be in favour of just supporting the format `CHROMOSOME_POSITION_REFALLELE_ALTALLELE`. There's an example on the homepage and as you said, ExAC uses the format `CHROMOSOME-POSITION-REFALLELE-ALTALLELE`.

**Comment by ElaineMcA** [comment]
Closing to create separate enhancement ticket.
