### ISSUE TITLE
Variant page - associated genes table

### ISSUE THREAD

**Issue by peatroot** [opentargets/genetics#60]
The associated genes table will be embedded within the variant page and will be **visible for any variant**.

## Minimal API
Below is the subset of the graphql schema relevant to this table. Until such time as the actual API gives full support, front-end will mock against this schema.
```
type Query {
    genesForVariant(variantId: String!): [GeneForVariant!]!
}

type GeneForVariant {
    id: String!
    symbol: String!
    overallScore: Float!
    qtls: [Qtl!]!
    intervals: [Interval!]!
    # functionalPredictions: TBD
}

type Qtl {
    id: String!
    name: String
    aggregateScore: Float!
    tissues: [QtlTissue!]!
}

type QtlTissue {
    id: String!
    name: String
    quantile: Float!
    beta: Float
    pval: Float
}

type Interval {
    id: String!
    name: String
    aggregateScore: Float!
    tissues: [IntervalTissue!]!
}

type IntervalTissue {
    id: String!
    name: String
    quantile: Float!
}
```

## Design
It is envisaged that there will be several tabs, such as **All** and **GTEx**, outlined below.

### All
For each gene, show summary values each source.

| Gene | Overall G2V | GTEx | PCHiC | Fantom5 | DHS | ... |
| -- | -- | -- | -- | -- | -- | -- |
| BRAF | 0.8 | 0.6 | 0.6 | N/A | N/A | |

### GTEx
For each gene, show GTEx broken down by tissue (could be heatmap/dot plot, since there might be pval and beta to display).

| Gene | T1 | T2 | T3 | ... |
| -- | -- | -- | -- | -- |
| BRAF | 0.8 | 0.6 | 0.6 | |

More TBD.

**Comment by peatroot** [comment]
@mkarmona, can you give your go/no-go for the above schema please? If acceptable, I can start mocking.

I spoke with @edm1 about this yesterday. Here's a brief summary of my understanding:
* the three bucket types (`qtls`, `intervals`, `functionalPredictions`) will be fixed
* the bucket contents are arrays and can therefore be dynamic
* any individual `Qtl` or `Interval` (or `FunctionalPrediction` when defined) must conform to the corresponding types above

**Comment by mkarmona** [comment]
@peatroot I will review it this weekend

**Comment by mkarmona** [comment]
@mirandaio it is missing `fpred` informacion and probably more stuff and it is hard for me at the moment going into a very detailed way if it is going to fit on my api side. You could start with it but pretty sure it will change.

**Comment by mkarmona** [comment]
@peatroot @mirandaio 
```
type Query {
    genesForVariantStructure: G2VStructure!
    genesForVariant(variantId: String!): [GeneForVariant!]!
}

type G2VSchema {
  qtl: [SchemaElement!]! 
  interval: [SchemaElement!]!
  functionalPredictions: [SchemaElement!]!
}

type  SchemaElement {
  id: String
  tissues: [Tissue!]!
}

type GeneForVariant {
    id: String!
    symbol: String!
    overallScore: Float!
    qtls: [Qtl!]!
    intervals: [Interval!]!
    functionalPredictions: [FunctionalPrediction!]!
}

type FunctionalPrediction {
  id: String!
  name: String
  aggregateScore: Float!
  tissues: [FPEffect!]!
}

type FPEffect {
  tissue: Tissue!
  maxScore: Float!
  maxScoreId: String!
}

type Qtl {
    id: String!
    name: String
    aggregateScore: Float!
    tissues: [QtlTissue!]!
}

type QtlTissue {
    tissue: Tissue!
    quantile: Float!
    beta: Float
    pval: Float
}

type Interval {
    id: String!
    name: String
    aggregateScore: Float!
    tissues: [IntervalTissue!]!
}

type IntervalTissue {
    tissue: Tissue!
    quantile: Float!
}

type Tissue {
  id: String!
  name: String
}
```

**Comment by mkarmona** [comment]
@peatroot @mirandaio This api, genes for variant, is done and deployed. You can find the final schema  on the schema definition page at [this url](https://open-targets-genetics.appspot.com/graphql/schema)
There is only one thing missing and is the gene information apart from the ID as gene dictionary is incomplete and I am waiting for a new completed version to update and use it.
