### ISSUE TITLE
Variant page - associated index variants table

### ISSUE THREAD

**Issue by peatroot** [opentargets/genetics#61]
The associated index variants table will be embedded within the variant page and will be **visible for tag variants**.

## Minimal API
Below is the subset of the graphql schema relevant to this table. Until such time as the actual API gives full support, front-end will mock against this schema.
```
type Query {
    indexVariantsAndStudiesForTagVariant(variantId: String!): IndexVariantsAndStudiesForTagVariant
}
type IndexVariantsAndStudiesForTagVariant {
    rows: [IndexVariantAndStudyForTagVariant!]!
}
type IndexVariantAndStudyForTagVariant {
    indexVariantId: String!
    indexVariantRsId: String!
    studyId: String!
    traitReported: String!
    pval: Float!

    # publication info
    pmid: String
    pubDate: String
    pubJournal: String
    pubTitle: String
    pubAuthor: String
    nTotal: Int # n_initial + n_replication
    nCases: Int # n_cases

    # ld info is optional; but expect all or none of the following
    overallR2: Float # 0.7 - 1
    afr1000GProp: Float # 0 - 1
    amr1000GProp: Float
    eas1000GProp: Float
    eur1000GProp: Float
    sas1000GProp: Float

    # finemapping is optional; but expect all or none of the following
    log10Abf: Float # -inf - +inf
    posteriorProbability: Float # 0 - 1
}
```

## Design
For the variant on whose page we are, **that is a tag variant**, show the index variant and studies it is associated with.

| Index Variant | Index Variant RSID | Study | Reported Trait | p-value | LD | log10(Approx Bayes Factor) | Posterior Prob | ... |
| -- | -- | -- | -- | -- | -- |  -- | -- | -- |
| (link to variant page) 3_1000200_A_T | rs123 | (link to study page using `<studyId>`) `<title> <author> <year> <journal>` | Blood protein levels | 5e-11 | 0.78 | 1.87 | 0.0023 | |

**Comment by peatroot** [comment]
@mkarmona, just updated this schema following discussion with Ed. As we understand it, the above could be pulled from the d2v2g table ignoring the g part and fixing the tag variant. Alternatively, you could build a derived table that contains (study, tag variant, index variant) triples along with the fields above. The query is almost identical for #63, but with index variant fixed instead of tag variant.

**Comment by peatroot** [comment]
@opentargets/genetics, can you please take a look at https://admiring-dubinsky-cb7f95.netlify.com/variant/1_100314838_C_T (third table) and comment on the following:
* Are the column names correct?
* What should the help text be in each column (there will be a pop-up tooltip)?
* Are we missing anything?

**Comment by edm1** [comment]
- Main title should show rsid in brackets after variant ID

**Associated genes**
- Title = 'Assigned genes'
- Subtitle = 'Which genes are functionally implicated by this variant?'

Existing columns:
- gene = 'Gene'
- g2v_score = 'Confidence' [High | Medium | Low | None]
- other columns to do later

**Associated studies**
See Issue #29 

** Associated index variant **
Title = 'GWAS lead variants'
Subtitle = 'What GWAS lead variants are linked with this variant?'

Column names:
- indexVariant = 'Variant'
- indexVariantRsid = 'rsID'
- StudyId = 'Study ID'
- traitReported = 'Trait'
- pval = 'P-value'
- pmid = 'PMID'
- combined pub = Author et al (year)
- no journal information
- nTotal = 'Study N'
- no case numbers
- overallR2 = 'LD (R-squared)'
  - tooltip = 'Linkage disequilibrium with the queried variant'
- don't show log10ABF or posteriorProbaility
- Column titled 'Is in 95% Credible Set' [True|False|No information]

** Associated tag variants **
Title = 'Tag variants'
Subtitle = 'Which variants tag (through LD or finemapping) this lead variant?'

Column names:
- indexVariant = 'Variant'
- indexVariantRsid = 'rsID'
- StudyId = 'Study ID'
- traitReported = 'Trait'
- pval = 'P-value'
- pmid = 'PMID'
- combined pub = Author et al (year)
- no journal information
- nTotal = 'Study N'
- no case numbers
- overallR2 = 'LD (R-squared)'
  - tooltip = 'Linkage disequilibrium with the queried variant'
- Column titled 'Is in 95% Credible Set' [True|False|No information]
- posteriorProbaility = 'Posterior probability'
  - tooltip = 'Posterior probability from finemapping that this tag variant is causal'
- don't show log10ABF

Other ---------

It would be nice (but not absolutely necessary) to have additional information (from the Ensembl API?) about the variant at the top of the page. Depending on what is available from Ensembl:
- Minor allele frequency (in different populations)
- Most severe consequence across any gene (this is available from Ensembl). We only have per gene consequences.

Notes, Ed to discuss with Miguel:
- For column 'Is in 95% Credible Set', we need to add an additional column showing whether finemapping was conducted (study ID will appear in finemapping table)
- log odds to be converted to ORs for case-control

Notes for FAQ:
- PheWAS uses UK Biobank (v1) only. GWAS CAtalog will be included later.
- Beta is log odds ratio for case-control studies.
- What does it mean to for variants to be linked? LD or credible set.

**Comment by peatroot** [comment]
For sections *associated genes*, *associated index variants* and *associated tag variants*, see https://github.com/opentargets/genetics-app/pull/29.

Otherwise:
* Minor allele frequency is raised elsewhere
* Most severe consequence is raised as https://github.com/opentargets/genetics/issues/87

For PheWAS section see comments in https://github.com/opentargets/genetics/issues/29

**Comment by mkarmona** [comment]
@peatroot done and deployed at API side.
