### ISSUE TITLE
Variant page - associated tag variants table

### ISSUE THREAD

**Issue by peatroot** [opentargets/genetics#63]
The associated tag variants table will be embedded within the variant page and will be **visible for index variants**.

## Minimal API
Below is the subset of the graphql schema relevant to this table. Until such time as the actual API gives full support, front-end will mock against this schema.
```
type Query {
    tagVariantsAndStudiesForIndexVariant(variantId: String!): TagVariantsAndStudiesForIndexVariant
}
type TagVariantsAndStudiesForIndexVariant {
    rows: [TagVariantAndStudyForIndexVariant!]!
}
type TagVariantAndStudyForIndexVariant {
    tagVariantId: String!
    tagVariantRsId: String!
    studyId: String!
    traitReported: String!
    pval: Float!

    # publication info
    pmid: String
    pubDate: String
    pubJournal: String
    pubTitle: String
    pubAuthor: String
    nTotal: Int # n_initial + n_replication
    nCases: Int # n_cases

    # ld info is optional; but expect all or none of the following
    overallR2: Float # 0.7 - 1
    afr1000GProp: Float # 0 - 1
    amr1000GProp: Float
    eas1000GProp: Float
    eur1000GProp: Float
    sas1000GProp: Float

    # finemapping is optional; but expect all or none of the following
    log10Abf: Float # -inf - +inf
    posteriorProbability: Float # 0 - 1
}
```

## Design
For the variant on whose page we are, **that is an index variant**, show the tag variants and studies it is associated with.

| Tag Variant | Tag Variant RSID | Study | Reported Trait | p-value | LD | log10(Approx Bayes Factor) | Posterior Prob | ... |
| -- | -- | -- | -- | -- | -- |  -- | -- | -- |
| (link to variant page) 3_1000200_A_T | rs123 | (link to study page using `<studyId>`) `<title> <author> <year> <journal>` | Blood protein levels | 5e-11 | 0.78 | 1.87 | 0.0023 | |

**Comment by mkarmona** [comment]
@peatroot @mirandaio here you can find new modifications made to the API. Mainly it groups variant and study objects as entities wrapping their own fields
```
"This object represent a link between a triple (study, trait, index_variant) and a tag variant via an expansion method (either ldExpansion or FineMapping)"
type IndexVariantAssociation {
  "Tag variant ID as ex. 1_12345_A_T"
  tagVariant: Variant!

  "study ID"
  study: Study!

  "p-val between a study and an the provided index variant"
  pval: Float!

  "n total cases (n initial + n replication)"
  nTotal: Int!

  "n cases"
  nCases: Int!

  "study ID"
  overallR2: Float
  afr1000GProp: Float
  amr1000GProp: Float
  eas1000GProp: Float
  eur1000GProp: Float
  sas1000GProp: Float
  log10Abf: Float
  posteriorProbability: Float
}
```
and this is a query looks like
```
  tagVariantsAndStudiesForIndexVariant(variantId:"1_170042536_C_T", pageIndex:0, pageSize:1) {
    associations {
      tagVariant {
        id
        rsId
        chromosome
      }
      study {
        studyId
        traitCode
        pubJournal
      }
      pval
      nCases
      nTotal
      overallR2
      eur1000GProp
      afr1000GProp
      amr1000GProp
      eas1000GProp
      sas1000GProp
      log10Abf
      posteriorProbability
    }
  }
```
You can try online [here](https://open-targets-genetics.appspot.com/graphql/browser?operationName=v2d&query=query%20v2d%20%7B%0A%20%20tagVariantsAndStudiesForIndexVariant(variantId%3A%221_170042536_C_T%22%2C%20pageIndex%3A0%2C%20pageSize%3A1)%20%7B%0A%20%20%20%20associations%20%7B%0A%20%20%20%20%20%20tagVariant%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20rsId%0A%20%20%20%20%20%20%20%20chromosome%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20study%20%7B%0A%20%20%20%20%20%20%20%20studyId%0A%20%20%20%20%20%20%20%20traitCode%0A%20%20%20%20%20%20%20%20pubJournal%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20pval%0A%20%20%20%20%20%20nCases%0A%20%20%20%20%20%20nTotal%0A%20%20%20%20%20%20overallR2%0A%20%20%20%20%20%20eur1000GProp%0A%20%20%20%20%20%20afr1000GProp%0A%20%20%20%20%20%20amr1000GProp%0A%20%20%20%20%20%20eas1000GProp%0A%20%20%20%20%20%20sas1000GProp%0A%20%20%20%20%20%20log10Abf%0A%20%20%20%20%20%20posteriorProbability%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)
