### ISSUE TITLE
V2D table does not contain n_total

### ISSUE THREAD

**Issue by mkarmona** [opentargets/genetics#66]
I missed n_total from original file

**Comment by edm1** [comment]
A total sample size is not reported by GWAS Catalog. It is separated into `n_initial` and `n_replication`. I have discussed with @MayaGhoussaini, since I have included the minimum P-value for each indexVariant for each study we think it is best that `n_total` should equal the sum of `n_initial` and `n_replication`.

**Comment by mkarmona** [comment]
great @edm1 thanks a lot. Here a result using v2d with toploci and expansions to compute it while I get the summary stats processed and loaded. I noticed I am also missing the n_cases as I made the mistake of missing that column.

### Input
Variant ID `6_88310327_G_A`

### Query

```sql
SELECT 
    trait_reported, 
    stid, 
    any(pval), 
    any(n_initial) AS n_initial, 
    any(n_replication) AS n_replication, 
    n_initial + n_replication AS n_total
FROM ot.v2d_by_chrpos 
PREWHERE (chr_id = '6') AND (position = 88310327) AND (variant_id = '6_88310327_G_A')
GROUP BY 
    trait_reported, 
    stid

┌─trait_reported─────────────────────────────────────────────────────────────────────────────────┬─stid───────┬─any(pval)─┬─n_initial─┬─n_replication─┬─n_total
─┐
│ Coronary atherosclerosis (increased number of diseased vessels) (traffic exposure interaction) │ GCST004224 │  0.000007 │      2100 │             0 │    2100 │
│ Obesity-related traits                                                                         │ GCST001762 │  0.000004 │       815 │             0 │     815 │
└────────────────────────────────────────────────────────────────────────────────────────────────┴────────────┴───────────┴───────────┴───────────────┴────────
─┘
``
