### ISSUE TITLE
Beta review of ASHG prototype

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/genetics#76]
Month-end demo in advance of final iteration and test cycle.

**Comment by ElaineMcA** [comment]
Meeting scheduled for review 30Aug2018.

DECISION 20Aug2018: Focused review of Gecko plot as most complex and thus priority for testing with real data for all.

Notes from discussions here:

https://docs.google.com/document/d/1Y9K0ZTkMFHfA6Q-HSIFljJDimQ7aqHOwYIYi7dHUyZU/edit#heading=h.854al3qxj8nr

**Comment by ElaineMcA** [comment]
Next review scheduled for 07Sep2018 to review with real data where possible.

**Comment by peatroot** [comment]
In the calendar now.
