### ISSUE TITLE
Make UK Biobank trait category map to sort/colour PheWAS plot

### ISSUE THREAD

**Issue by edm1** [opentargets/genetics#78]
To be used in a future version of the PheWAS plot.

Biogen may have a pre-existing map for UK Biobank traits (as seen in a presentation of theirs). Alternatively it could be based on EFO codes, e.g. child terms of [Disease](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000408#). Not all UKB traits have an EFO though.

**Comment by emschmidt** [comment]
PheWAS categories for the Neal UKB summary statistics were obtained from the Oxford BIG browser (http://big.stats.ox.ac.uk/). Table with phenostring, field code, and category for 2,420 traits is located here:
gs://uk_biobank_data/em21/neale_summary_statistics_20170915/PheWAS_categories/phenotypes.tsv
