### ISSUE TITLE
Variant page - add most severe consequence across any gene

### ISSUE THREAD

**Issue by peatroot** [opentargets/genetics#87]
The most severe consequence across any gene is available from Ensembl.

We only have per gene consequences from our V2G assignment and we wouldn't see that the variant is e.g. intronic (between genes).

Consider adding as top-level info on the variant.

**Comment by mkarmona** [comment]
@peatroot @elipapa @edm1 I dont think this is going to be possible at the moment

**Comment by mkarmona** [comment]
@peatroot @edm1 @elipapa I am not sure how should I address this issue as we decided to filter intergenic from v2g (`overall_score > 0` and as you know vep is the only giving `overall_score == 0`).  I don't see why should we reproduce all websites around?
We are already including all vep consequences (snv and short variantions) which generate pairs of (variant, gene) by a `fpred`.

**Comment by peatroot** [comment]
@mkarmona @edm1, propose making this a v2.0 feature?

**Comment by mkarmona** [comment]
this won't be possible at the moment in the way we have the data
structured. this will be checked post October @pearoot

**Comment by edm1** [comment]
This will be included in the new variant annotation https://github.com/opentargets/genetics/issues/229
