### ISSUE TITLE
Support regional querying of POSTGAP data by GWAS variant

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/genetics#89]
@peatroot commented on [Thu Feb 01 2018](https://github.com/opentargets/rest_api/issues/149)

## Requirements
* To function as we believe users will expect, the POSTGAP genome browser needs the `evidence/filter` endpoint to support parameters `chrom`, `start` and `end` (or similar names).
* When these parameters are used, the response should return all POSTGAP evidence strings such that the gene **OR** variant **OR** GWAS variant is within the region `chrom:start-end`.

## Background
This is related to https://github.com/opentargets/rest_api/issues/148.

**Comment by ElaineMcA** [comment]
@peatroot : please confirm if still relevant.

**Comment by peatroot** [comment]
Not relevant.
