### ISSUE TITLE
Ensure scroll-to-top triggered on route change

### ISSUE THREAD

**Issue by peatroot** [opentargets/genetics#99]
Currently, following internal links preserves the scroll state. This is in most cases not desirable, but one exception is the locus page, which updates the url whenever the locus start and end change. For discussion and possible solutions, see https://github.com/ReactTraining/react-router/issues/2019.

**Comment by mirandaio** [comment]
This has been fixed in this PR https://github.com/opentargets/genetics-app/pull/38
